In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## 2025

In [2]:
Conditions_25=pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Conditions_Jun2025_NC.csv')
Conditions_25

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Condition,Count,Footnote
0,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,All other conditions,337,-
1,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,Brain disease or condition (non-traumatic),60,-
2,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,Brain injury (traumatic),79,-
3,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,Hip or femur fracture,114,-
4,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,"Hip or knee replacement, amputation or other b...",175,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,34T155,DURHAM REGIONAL HOSPITAL,3643 N ROXBORO ROAD,BOX 52,DURHAM,NC,27704,Durham,(919) 470-7226,4,"Hip or knee replacement, amputation or other b...",58,-
230,34T155,DURHAM REGIONAL HOSPITAL,3643 N ROXBORO ROAD,BOX 52,DURHAM,NC,27704,Durham,(919) 470-7226,4,Nervous system disorder (excluding stroke),13,-
231,34T155,DURHAM REGIONAL HOSPITAL,3643 N ROXBORO ROAD,BOX 52,DURHAM,NC,27704,Durham,(919) 470-7226,4,Spinal cord disease or condition (non-traumatic),51,-
232,34T155,DURHAM REGIONAL HOSPITAL,3643 N ROXBORO ROAD,BOX 52,DURHAM,NC,27704,Durham,(919) 470-7226,4,Spinal cord injury (traumatic),Less than 11,1
233,34T155,DURHAM REGIONAL HOSPITAL,3643 N ROXBORO ROAD,BOX 52,DURHAM,NC,27704,Durham,(919) 470-7226,4,Stroke,100,-

In [3]:
Conditions_25= Conditions_25[['County/Parish','Condition','Count']]
Conditions_25

,County/Parish,Condition,Count
0,Buncombe,All other conditions,337
1,Buncombe,Brain disease or condition (non-traumatic),60
2,Buncombe,Brain injury (traumatic),79
3,Buncombe,Hip or femur fracture,114
4,Buncombe,"Hip or knee replacement, amputation or other b...",175
...,...,...,...
229,Durham,"Hip or knee replacement, amputation or other b...",58
230,Durham,Nervous system disorder (excluding stroke),13
231,Durham,Spinal cord disease or condition (non-traumatic),51
232,Durham,Spinal cord injury (traumatic),Less than 11
233,Durham,Stroke,100

In [4]:
rows_to_drop= Conditions_25.loc[(Conditions_25['Count']=='Not Available') | (Conditions_25['Count']=='Less than 11')]

In [5]:
Conditions_25=Conditions_25.drop(rows_to_drop.index, axis=0)
Conditions_25

    County/Parish                                          Condition Count
0        Buncombe                               All other conditions   337
1        Buncombe         Brain disease or condition (non-traumatic)    60
2        Buncombe                           Brain injury (traumatic)    79
3        Buncombe                              Hip or femur fracture   114
4        Buncombe  Hip or knee replacement, amputation or other b...   175
..            ...                                                ...   ...
228        Durham                              Hip or femur fracture    15
229        Durham  Hip or knee replacement, amputation or other b...    58
230        Durham         Nervous system disorder (excluding stroke)    13
231        Durham   Spinal cord disease or condition (non-traumatic)    51
233        Durham                                             Stroke   100

[146 rows x 3 columns]

In [6]:
Conditions_25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146 entries, 0 to 233
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   County/Parish  146 non-null    object
 1   Condition      146 non-null    object
 2   Count          146 non-null    object
dtypes: object(3)
memory usage: 4.6+ KB

In [7]:
Conditions_25['Count']=Conditions_25['Count'].astype(str).astype(float)

In [8]:
Conditions_grouped_25 = Conditions_25.groupby(['County/Parish', 'Condition'])['Count'].sum().to_frame()

In [9]:
Conditions_grouped_25=Conditions_grouped_25.reset_index()
Conditions_grouped_25

    County/Parish                                          Condition  Count
0        Buncombe                               All other conditions  337.0
1        Buncombe         Brain disease or condition (non-traumatic)   60.0
2        Buncombe                           Brain injury (traumatic)   79.0
3        Buncombe                              Hip or femur fracture  114.0
4        Buncombe  Hip or knee replacement, amputation or other b...  175.0
..            ...                                                ...    ...
115          Wake  Hip or knee replacement, amputation or other b...  156.0
116          Wake         Nervous system disorder (excluding stroke)   38.0
117          Wake   Spinal cord disease or condition (non-traumatic)   70.0
118          Wake                     Spinal cord injury (traumatic)   33.0
119          Wake                                             Stroke  261.0

[120 rows x 3 columns]

In [10]:
Conditions_grouped_25['Percent_Condition 2025'] = (
    Conditions_grouped_25.groupby('County/Parish')['Count']
    .transform(lambda x: x / x.sum() * 100)
)

In [11]:
Conditions_grouped_25

,County/Parish,Condition,Count,Percent_Condition 2025
0,Buncombe,All other conditions,337.0,28.343146
1,Buncombe,Brain disease or condition (non-traumatic),60.0,5.046257
2,Buncombe,Brain injury (traumatic),79.0,6.644239
3,Buncombe,Hip or femur fracture,114.0,9.587889
4,Buncombe,"Hip or knee replacement, amputation or other b...",175.0,14.718251
...,...,...,...,...
115,Wake,"Hip or knee replacement, amputation or other b...",156.0,17.488789
116,Wake,Nervous system disorder (excluding stroke),38.0,4.260090
117,Wake,Spinal cord disease or condition (non-traumatic),70.0,7.847534
118,Wake,Spinal cord injury (traumatic),33.0,3.699552
119,Wake,Stroke,261.0,29.260090

In [12]:
Conditions_grouped_25.loc[Conditions_grouped_25['County/Parish']=='Rowan']

,County/Parish,Condition,Count,Percent_Condition 2025
102,Rowan,Hip or femur fracture,13.0,10.743802
103,Rowan,"Hip or knee replacement, amputation or other b...",14.0,11.570248
104,Rowan,Nervous system disorder (excluding stroke),50.0,41.322314
105,Rowan,Spinal cord disease or condition (non-traumatic),12.0,9.917355
106,Rowan,Stroke,32.0,26.446281

Finding the condition with the highest % of occurence by county

In [13]:
idx = Conditions_grouped_25.groupby('County/Parish')['Percent_Condition 2025'].idxmax()
idx

County/Parish
Buncombe         0
Catawba         16
Craven          17
Cumberland      26
Durham          36
Forsyth         45
Guilford        53
Lenoir          54
Mecklenburg     67
Moore           71
Nash            75
New Hanover     83
Orange          84
Pitt           101
Rowan          104
Vance          110
Wake           119
Name: Percent_Condition 2025, dtype: int64

In [14]:
highest_conditions_county25= Conditions_grouped_25.loc[idx].reset_index(drop=True)
highest_conditions_county25

,County/Parish,Condition,Count,Percent_Condition 2025
0,Buncombe,All other conditions,337.0,28.343146
1,Catawba,Stroke,131.0,37.321937
2,Craven,All other conditions,67.0,27.459016
3,Cumberland,"Hip or knee replacement, amputation or other b...",136.0,22.857143
4,Durham,Stroke,100.0,31.347962
5,Forsyth,Stroke,504.0,30.788027
6,Guilford,Stroke,348.0,45.609436
7,Lenoir,All other conditions,64.0,31.683168
8,Mecklenburg,Stroke,745.0,30.346232
9,Moore,Stroke,82.0,49.696970
10,Nash,Stroke,128.0,34.688347
11,New Hanover,Stroke,175.0,27.386541
12,Orange,All other conditions,152.0,29.400387
13,Pitt,Stroke,287.0,27.649326
14,Rowan,Nervous system disorder (excluding stroke),50.0,41.322314
15,Vance,Stroke,55.0,34.591195
16,Wake,Stroke,261.0,29.260090

In [15]:
min_condition=Conditions_grouped_25['Percent_Condition 2025'].min()
min_condition

0.794135613927917

In [16]:
Conditions_grouped_25.loc[Conditions_grouped_25['Percent_Condition 2025']==0.794135613927917]

,County/Parish,Condition,Count,Percent_Condition 2025
44,Forsyth,Spinal cord injury (traumatic),13.0,0.794136

In [17]:
max_condition=Conditions_grouped_25['Percent_Condition 2025'].max()
max_condition

49.696969696969695

In [18]:
Conditions_grouped_25.loc[Conditions_grouped_25['Percent_Condition 2025']==49.696969696969695]

   County/Parish Condition  Count  Percent_Condition 2025
71         Moore    Stroke   82.0                49.69697

In [19]:
total_counts_25= Conditions_grouped_25.groupby('Condition')['Count'].sum().reset_index()
total_counts_25

                                           Condition   Count
0                               All other conditions  2684.0
1         Brain disease or condition (non-traumatic)   763.0
2                           Brain injury (traumatic)   531.0
3                              Hip or femur fracture   976.0
4  Hip or knee replacement, amputation or other b...  1748.0
5         Nervous system disorder (excluding stroke)   608.0
6   Spinal cord disease or condition (non-traumatic)   690.0
7                     Spinal cord injury (traumatic)   154.0
8                                             Stroke  3501.0

In [20]:
grand_total= total_counts_25['Count'].sum()
grand_total

np.float64(11655.0)

In [21]:
total_counts_25['pct conditions 2025']= (total_counts_25['Count']/grand_total) * 100
total_counts_25

,Condition,Count,pct conditions 2025
0,All other conditions,2684.0,23.028743
1,Brain disease or condition (non-traumatic),763.0,6.546547
2,Brain injury (traumatic),531.0,4.555985
3,Hip or femur fracture,976.0,8.374088
4,"Hip or knee replacement, amputation or other b...",1748.0,14.997855
5,Nervous system disorder (excluding stroke),608.0,5.216645
6,Spinal cord disease or condition (non-traumatic),690.0,5.920206
7,Spinal cord injury (traumatic),154.0,1.321321
8,Stroke,3501.0,30.038610

In [22]:
Conditions_grouped_25.to_csv('Conditions_grouped_25.csv')

## 2024

In [23]:
Conditions_24=pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Conditions_Jun2024.csv')
Conditions_24.head()

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Condition,Count,Footnote
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,All other conditions,385,-
1,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain disease or condition (non-traumatic),157,-
2,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain injury (traumatic),48,-
3,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Hip or femur fracture,190,-
4,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,"Hip or knee replacement, amputation or other b...",364,-

In [24]:
Conditions_24= Conditions_24[['County/Parish','State','Condition','Count']]

In [25]:
rows_to_drop= Conditions_24.loc[(Conditions_24['Count']=='Not Available') | (Conditions_24['Count']=='Less than 11')]
rows_to_drop

,County/Parish,State,Condition,Count
7,Jefferson,AL,Spinal cord injury (traumatic),Less than 11
16,Montgomery,AL,Spinal cord injury (traumatic),Less than 11
34,Houston,AL,Spinal cord injury (traumatic),Less than 11
43,Shelby,AL,Spinal cord injury (traumatic),Less than 11
52,Etowah,AL,Spinal cord injury (traumatic),Less than 11
...,...,...,...,...
10892,WASHINGTON,LA,Brain injury (traumatic),Less than 11
10893,WASHINGTON,LA,Hip or femur fracture,Less than 11
10896,WASHINGTON,LA,Spinal cord disease or condition (non-traumatic),Less than 11
10897,WASHINGTON,LA,Spinal cord injury (traumatic),Less than 11
10906,Caddo,LA,Spinal cord injury (traumatic),Less than 11

In [26]:
Conditions_24=Conditions_24.drop(rows_to_drop.index, axis=0)

In [27]:
Conditions_24['Count']=Conditions_24['Count'].astype(str).astype(float)
Conditions_24

,County/Parish,State,Condition,Count
0,Jefferson,AL,All other conditions,385.0
1,Jefferson,AL,Brain disease or condition (non-traumatic),157.0
2,Jefferson,AL,Brain injury (traumatic),48.0
3,Jefferson,AL,Hip or femur fracture,190.0
4,Jefferson,AL,"Hip or knee replacement, amputation or other b...",364.0
...,...,...,...,...
10912,Caddo,LA,"Hip or knee replacement, amputation or other b...",114.0
10913,Caddo,LA,Nervous system disorder (excluding stroke),100.0
10914,Caddo,LA,Spinal cord disease or condition (non-traumatic),19.0
10915,Caddo,LA,Spinal cord injury (traumatic),11.0
10916,Caddo,LA,Stroke,128.0

In [28]:
Conditions_24=Conditions_24.loc[Conditions_24['State']=='NC']
Conditions_24

,County/Parish,State,Condition,Count
6372,Buncombe,NC,All other conditions,321.0
6373,Buncombe,NC,Brain disease or condition (non-traumatic),57.0
6374,Buncombe,NC,Brain injury (traumatic),82.0
6375,Buncombe,NC,Hip or femur fracture,136.0
6376,Buncombe,NC,"Hip or knee replacement, amputation or other b...",187.0
...,...,...,...,...
6600,Durham,NC,Hip or femur fracture,29.0
6601,Durham,NC,"Hip or knee replacement, amputation or other b...",43.0
6602,Durham,NC,Nervous system disorder (excluding stroke),16.0
6603,Durham,NC,Spinal cord disease or condition (non-traumatic),41.0
6605,Durham,NC,Stroke,83.0

In [29]:
Conditions_grouped_24 = Conditions_24.groupby(['County/Parish', 'Condition'])['Count'].sum().to_frame()

In [30]:
Conditions_grouped_24=Conditions_grouped_24.reset_index()

In [31]:
Conditions_grouped_24

    County/Parish                                          Condition  Count
0        Buncombe                               All other conditions  321.0
1        Buncombe         Brain disease or condition (non-traumatic)   57.0
2        Buncombe                           Brain injury (traumatic)   82.0
3        Buncombe                              Hip or femur fracture  136.0
4        Buncombe  Hip or knee replacement, amputation or other b...  187.0
..            ...                                                ...    ...
113          Wake  Hip or knee replacement, amputation or other b...  181.0
114          Wake         Nervous system disorder (excluding stroke)   25.0
115          Wake   Spinal cord disease or condition (non-traumatic)   66.0
116          Wake                     Spinal cord injury (traumatic)   24.0
117          Wake                                             Stroke  284.0

[118 rows x 3 columns]

In [32]:
Conditions_grouped_24['Percent_Condition'] = (
    Conditions_grouped_24.groupby('County/Parish')['Count']
    .transform(lambda x: x / x.sum() * 100)
)
Conditions_grouped_24

,County/Parish,Condition,Count,Percent_Condition
0,Buncombe,All other conditions,321.0,26.140065
1,Buncombe,Brain disease or condition (non-traumatic),57.0,4.641694
2,Buncombe,Brain injury (traumatic),82.0,6.677524
3,Buncombe,Hip or femur fracture,136.0,11.074919
4,Buncombe,"Hip or knee replacement, amputation or other b...",187.0,15.228013
...,...,...,...,...
113,Wake,"Hip or knee replacement, amputation or other b...",181.0,18.545082
114,Wake,Nervous system disorder (excluding stroke),25.0,2.561475
115,Wake,Spinal cord disease or condition (non-traumatic),66.0,6.762295
116,Wake,Spinal cord injury (traumatic),24.0,2.459016
117,Wake,Stroke,284.0,29.098361

In [33]:
total_counts_24= Conditions_grouped_24.groupby('Condition')['Count'].sum().reset_index()
total_counts_24

                                           Condition   Count
0                               All other conditions  2604.0
1         Brain disease or condition (non-traumatic)   728.0
2                           Brain injury (traumatic)   471.0
3                              Hip or femur fracture   984.0
4  Hip or knee replacement, amputation or other b...  1715.0
5         Nervous system disorder (excluding stroke)   591.0
6   Spinal cord disease or condition (non-traumatic)   707.0
7                     Spinal cord injury (traumatic)   105.0
8                                             Stroke  3147.0

In [34]:
grand_total= Conditions_grouped_24['Count'].sum()
grand_total

np.float64(11052.0)

In [35]:
total_counts_24['pct conditions 2024']= (total_counts_24['Count']/grand_total) * 100
total_counts_24

,Condition,Count,pct conditions 2024
0,All other conditions,2604.0,23.561346
1,Brain disease or condition (non-traumatic),728.0,6.587043
2,Brain injury (traumatic),471.0,4.261672
3,Hip or femur fracture,984.0,8.903366
4,"Hip or knee replacement, amputation or other b...",1715.0,15.517553
5,Nervous system disorder (excluding stroke),591.0,5.347448
6,Spinal cord disease or condition (non-traumatic),707.0,6.397032
7,Spinal cord injury (traumatic),105.0,0.950054
8,Stroke,3147.0,28.474484

Finding the condition with the highest % of occurence by county

In [36]:
idx = Conditions_grouped_24.groupby('County/Parish')['Percent_Condition'].idxmax()
idx

County/Parish
Buncombe         0
Catawba         15
Craven          20
Cumberland      28
Durham          35
Forsyth         43
Guilford        51
Lenoir          52
Mecklenburg     65
Moore           70
Nash            74
New Hanover     82
Orange          83
Pitt            91
Rowan          102
Vance          105
Wake           117
Name: Percent_Condition, dtype: int64

In [37]:
highest_percent_condition_county24= Conditions_grouped_24.loc[idx].reset_index(drop=True)
highest_percent_condition_county24

,County/Parish,Condition,Count,Percent_Condition
0,Buncombe,All other conditions,321.0,26.140065
1,Catawba,Stroke,90.0,29.508197
2,Craven,Stroke,53.0,28.961749
3,Cumberland,Stroke,118.0,21.771218
4,Durham,Stroke,83.0,25.937500
5,Forsyth,Stroke,436.0,28.912467
6,Guilford,Stroke,345.0,43.781726
7,Lenoir,All other conditions,52.0,30.588235
8,Mecklenburg,Stroke,654.0,27.688400
9,Moore,Stroke,73.0,41.954023
10,Nash,Stroke,95.0,30.158730
11,New Hanover,Stroke,191.0,30.906149
12,Orange,All other conditions,103.0,25.685786
13,Pitt,All other conditions,241.0,26.454446
14,Rowan,Nervous system disorder (excluding stroke),45.0,34.090909
15,Vance,All other conditions,42.0,35.294118
16,Wake,Stroke,284.0,29.098361

In [38]:
Conditions_grouped_24.to_csv('Conditions_grouped_24.csv')

## 2023

In [39]:
Conditions_23=pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Conditions_Jun2023.csv')
Conditions_23

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,Phone Number,CMS Region,Condition,Count,Footnote
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,All other conditions,359,-
1,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain disease or condition (non-traumatic),188,-
2,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain injury (traumatic),44,-
3,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Hip or femur fracture,194,-
4,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,"Hip or knee replacement, amputation or other b...",385,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10804,713029,SHREVEPORT REHABILITATION HOSPITAL LLC,1451 FERN CIRCLE,-,SHREVEPORT,LA,71105,Caddo,(318) 232-8880,6,"Hip or knee replacement, amputation or other b...",50,-
10805,713029,SHREVEPORT REHABILITATION HOSPITAL LLC,1451 FERN CIRCLE,-,SHREVEPORT,LA,71105,Caddo,(318) 232-8880,6,Nervous system disorder (excluding stroke),28,-
10806,713029,SHREVEPORT REHABILITATION HOSPITAL LLC,1451 FERN CIRCLE,-,SHREVEPORT,LA,71105,Caddo,(318) 232-8880,6,Spinal cord disease or condition (non-traumatic),Less than 11,1
10807,713029,SHREVEPORT REHABILITATION HOSPITAL LLC,1451 FERN CIRCLE,-,SHREVEPORT,LA,71105,Caddo,(318) 232-8880,6,Spinal cord injury (traumatic),Less than 11,1
10808,713029,SHREVEPORT REHABILITATION HOSPITAL LLC,1451 FERN CIRCLE,-,SHREVEPORT,LA,71105,Caddo,(318) 232-8880,6,Stroke,27,-

In [40]:
Conditions_23= Conditions_23[['County Name','State','Condition','Count']]

In [41]:
Conditions_23=Conditions_23.loc[Conditions_23['State']=='NC']

In [42]:
rows_to_drop= Conditions_23.loc[(Conditions_23['Count']=='Not Available') | (Conditions_23['Count']=='Less than 11')]

In [43]:
Conditions_23=Conditions_23.drop(rows_to_drop.index, axis=0).rename(columns={'County Name':'County/Parish'})

In [44]:
Conditions_23['Count']=Conditions_23['Count'].astype(str).astype(float)

In [45]:
Conditions_grouped_23 = Conditions_23.groupby(['County/Parish', 'Condition'])['Count'].sum().to_frame().reset_index()

In [46]:
Conditions_grouped_23['Percent_Condition'] = (
    Conditions_grouped_23.groupby('County/Parish')['Count']
    .transform(lambda x: x / x.sum() * 100)
)

In [47]:
Conditions_grouped_23.head()

,County/Parish,Condition,Count,Percent_Condition
0,Buncombe,All other conditions,298.0,25.147679
1,Buncombe,Brain disease or condition (non-traumatic),78.0,6.582278
2,Buncombe,Brain injury (traumatic),76.0,6.413502
3,Buncombe,Hip or femur fracture,107.0,9.029536
4,Buncombe,"Hip or knee replacement, amputation or other b...",150.0,12.658228

Finding the condition with the highest % of occurence by county

In [48]:
idx= Conditions_grouped_23.groupby('County/Parish')['Percent_Condition'].idxmax()
idx

County/Parish
Buncombe         8
Catawba         14
Craven          20
Cumberland      28
Durham          34
Forsyth         43
Guilford        51
Lenoir          55
Mecklenburg     64
Moore           69
Nash            74
New Hanover     82
Orange          83
Pitt            98
Rowan          103
Vance          109
Wake           118
Name: Percent_Condition, dtype: int64

In [49]:
highest_percent_conditions_county23 = Conditions_grouped_23.loc[idx].reset_index(drop=True)
highest_percent_conditions_county23

,County/Parish,Condition,Count,Percent_Condition
0,Buncombe,Stroke,332.0,28.016878
1,Catawba,Stroke,75.0,44.910180
2,Craven,Stroke,68.0,30.909091
3,Cumberland,Stroke,136.0,25.138632
4,Durham,Stroke,76.0,27.737226
5,Forsyth,Stroke,460.0,31.636864
6,Guilford,Stroke,299.0,42.471591
7,Lenoir,Stroke,60.0,46.153846
8,Mecklenburg,Stroke,646.0,28.877962
9,Moore,Stroke,54.0,44.262295
10,Nash,Stroke,122.0,33.333333
11,New Hanover,Stroke,215.0,37.261698
12,Orange,All other conditions,85.0,28.428094
13,Pitt,Stroke,251.0,29.739336
14,Rowan,Nervous system disorder (excluding stroke),35.0,24.137931
15,Vance,Stroke,37.0,33.333333
16,Wake,Stroke,299.0,29.516288

In [50]:
highest_percent_conditions_county23.to_csv('highest_percent_conditions_county23.csv')

Finding the total percent of each condition across all counties:

In [51]:
total_counts_23=Conditions_grouped_23.groupby('Condition')['Count'].sum().reset_index()
total_counts_23

                                           Condition   Count
0                               All other conditions  2253.0
1         Brain disease or condition (non-traumatic)   693.0
2                           Brain injury (traumatic)   460.0
3                              Hip or femur fracture   825.0
4  Hip or knee replacement, amputation or other b...  1482.0
5         Nervous system disorder (excluding stroke)   570.0
6   Spinal cord disease or condition (non-traumatic)   744.0
7                     Spinal cord injury (traumatic)   140.0
8                                             Stroke  3222.0

In [52]:
grand_total= total_counts_23['Count'].sum()
grand_total

np.float64(10389.0)

In [53]:
total_counts_23['pct condition 2023']=(total_counts_23['Count']/grand_total) *100
total_counts_23

,Condition,Count,pct condition 2023
0,All other conditions,2253.0,21.686399
1,Brain disease or condition (non-traumatic),693.0,6.670517
2,Brain injury (traumatic),460.0,4.427760
3,Hip or femur fracture,825.0,7.941092
4,"Hip or knee replacement, amputation or other b...",1482.0,14.265088
5,Nervous system disorder (excluding stroke),570.0,5.486572
6,Spinal cord disease or condition (non-traumatic),744.0,7.161421
7,Spinal cord injury (traumatic),140.0,1.347579
8,Stroke,3222.0,31.013572

In [54]:
Conditions_grouped_23.to_csv('Conditions_grouped_23.csv')

In [55]:
Combined_Conditions= pd.merge(Conditions_grouped_23, Conditions_grouped_24,
                              on='County/Parish',
                              how='inner')
Combined_Conditions

,County/Parish,Condition_x,Count_x,Percent_Condition_x,Condition_y,Count_y,Percent_Condition_y
0,Buncombe,All other conditions,298.0,25.147679,All other conditions,321.0,26.140065
1,Buncombe,All other conditions,298.0,25.147679,Brain disease or condition (non-traumatic),57.0,4.641694
2,Buncombe,All other conditions,298.0,25.147679,Brain injury (traumatic),82.0,6.677524
3,Buncombe,All other conditions,298.0,25.147679,Hip or femur fracture,136.0,11.074919
4,Buncombe,All other conditions,298.0,25.147679,"Hip or knee replacement, amputation or other b...",187.0,15.228013
...,...,...,...,...,...,...,...
869,Wake,Stroke,299.0,29.516288,"Hip or knee replacement, amputation or other b...",181.0,18.545082
870,Wake,Stroke,299.0,29.516288,Nervous system disorder (excluding stroke),25.0,2.561475
871,Wake,Stroke,299.0,29.516288,Spinal cord disease or condition (non-traumatic),66.0,6.762295
872,Wake,Stroke,299.0,29.516288,Spinal cord injury (traumatic),24.0,2.459016
873,Wake,Stroke,299.0,29.516288,Stroke,284.0,29.098361

In [56]:
Combined_total_pcts_condition= pd.merge(total_counts_23,total_counts_24,
                                        on = 'Condition',
                                        how= 'inner')

In [57]:
Combined_total_pcts_condition=pd.merge(Combined_total_pcts_condition, total_counts_25,
                                       on='Condition',
                                       how='inner')
Combined_total_pcts_condition

,Condition,Count_x,pct condition 2023,Count_y,pct conditions 2024,Count,pct conditions 2025
0,All other conditions,2253.0,21.686399,2604.0,23.561346,2684.0,23.028743
1,Brain disease or condition (non-traumatic),693.0,6.670517,728.0,6.587043,763.0,6.546547
2,Brain injury (traumatic),460.0,4.427760,471.0,4.261672,531.0,4.555985
3,Hip or femur fracture,825.0,7.941092,984.0,8.903366,976.0,8.374088
4,"Hip or knee replacement, amputation or other b...",1482.0,14.265088,1715.0,15.517553,1748.0,14.997855
5,Nervous system disorder (excluding stroke),570.0,5.486572,591.0,5.347448,608.0,5.216645
6,Spinal cord disease or condition (non-traumatic),744.0,7.161421,707.0,6.397032,690.0,5.920206
7,Spinal cord injury (traumatic),140.0,1.347579,105.0,0.950054,154.0,1.321321
8,Stroke,3222.0,31.013572,3147.0,28.474484,3501.0,30.038610

In [58]:
Combined_total_pcts_condition=Combined_total_pcts_condition[['Condition','pct condition 2023','pct conditions 2024','pct conditions 2025']]
Combined_total_pcts_condition

,Condition,pct condition 2023,pct conditions 2024,pct conditions 2025
0,All other conditions,21.686399,23.561346,23.028743
1,Brain disease or condition (non-traumatic),6.670517,6.587043,6.546547
2,Brain injury (traumatic),4.427760,4.261672,4.555985
3,Hip or femur fracture,7.941092,8.903366,8.374088
4,"Hip or knee replacement, amputation or other b...",14.265088,15.517553,14.997855
5,Nervous system disorder (excluding stroke),5.486572,5.347448,5.216645
6,Spinal cord disease or condition (non-traumatic),7.161421,6.397032,5.920206
7,Spinal cord injury (traumatic),1.347579,0.950054,1.321321
8,Stroke,31.013572,28.474484,30.038610

In [59]:
Combined_total_pcts_condition.to_csv('Combined_total_pcts_condition.csv')

Now looking at conditions that were most prevalent in each county across all three years:

In [60]:
dfs=[highest_percent_conditions_county23, highest_percent_condition_county24, highest_conditions_county25]

Combined_highest_pct_condition = dfs[0]

for i in range(1, len(dfs)):
    Combined_highest_pct_condition= pd.merge(Combined_highest_pct_condition, dfs[i], on = 'County/Parish', how ='inner')


Combined_highest_pct_condition

,County/Parish,Condition_x,Count_x,Percent_Condition_x,Condition_y,Count_y,Percent_Condition_y,Condition,Count,Percent_Condition 2025
0,Buncombe,Stroke,332.0,28.016878,All other conditions,321.0,26.140065,All other conditions,337.0,28.343146
1,Catawba,Stroke,75.0,44.910180,Stroke,90.0,29.508197,Stroke,131.0,37.321937
2,Craven,Stroke,68.0,30.909091,Stroke,53.0,28.961749,All other conditions,67.0,27.459016
3,Cumberland,Stroke,136.0,25.138632,Stroke,118.0,21.771218,"Hip or knee replacement, amputation or other b...",136.0,22.857143
4,Durham,Stroke,76.0,27.737226,Stroke,83.0,25.937500,Stroke,100.0,31.347962
5,Forsyth,Stroke,460.0,31.636864,Stroke,436.0,28.912467,Stroke,504.0,30.788027
6,Guilford,Stroke,299.0,42.471591,Stroke,345.0,43.781726,Stroke,348.0,45.609436
7,Lenoir,Stroke,60.0,46.153846,All other conditions,52.0,30.588235,All other conditions,64.0,31.683168
8,Mecklenburg,Stroke,646.0,28.877962,Stroke,654.0,27.688400,Stroke,745.0,30.346232
9,Moore,Stroke,54.0,44.262295,Stroke,73.0,41.954023,Stroke,82.0,49.696970
10,Nash,Stroke,122.0,33.333333,Stroke,95.0,30.158730,Stroke,128.0,34.688347
11,New Hanover,Stroke,215.0,37.261698,Stroke,191.0,30.906149,Stroke,175.0,27.386541
12,Orange,All other conditions,85.0,28.428094,All other conditions,103.0,25.685786,All other conditions,152.0,29.400387
13,Pitt,Stroke,251.0,29.739336,All other conditions,241.0,26.454446,Stroke,287.0,27.649326
14,Rowan,Nervous system disorder (excluding stroke),35.0,24.137931,Nervous system disorder (excluding stroke),45.0,34.090909,Nervous system disorder (excluding stroke),50.0,41.322314
15,Vance,Stroke,37.0,33.333333,All other conditions,42.0,35.294118,Stroke,55.0,34.591195
16,Wake,Stroke,299.0,29.516288,Stroke,284.0,29.098361,Stroke,261.0,29.260090

In [61]:
Combined_highest_pct_condition=Combined_highest_pct_condition[['County/Parish','Condition_x','Percent_Condition_x','Condition_y','Percent_Condition_y','Condition','Percent_Condition 2025']]
Combined_highest_pct_condition

,County/Parish,Condition_x,Percent_Condition_x,Condition_y,Percent_Condition_y,Condition,Percent_Condition 2025
0,Buncombe,Stroke,28.016878,All other conditions,26.140065,All other conditions,28.343146
1,Catawba,Stroke,44.910180,Stroke,29.508197,Stroke,37.321937
2,Craven,Stroke,30.909091,Stroke,28.961749,All other conditions,27.459016
3,Cumberland,Stroke,25.138632,Stroke,21.771218,"Hip or knee replacement, amputation or other b...",22.857143
4,Durham,Stroke,27.737226,Stroke,25.937500,Stroke,31.347962
5,Forsyth,Stroke,31.636864,Stroke,28.912467,Stroke,30.788027
6,Guilford,Stroke,42.471591,Stroke,43.781726,Stroke,45.609436
7,Lenoir,Stroke,46.153846,All other conditions,30.588235,All other conditions,31.683168
8,Mecklenburg,Stroke,28.877962,Stroke,27.688400,Stroke,30.346232
9,Moore,Stroke,44.262295,Stroke,41.954023,Stroke,49.696970
10,Nash,Stroke,33.333333,Stroke,30.158730,Stroke,34.688347
11,New Hanover,Stroke,37.261698,Stroke,30.906149,Stroke,27.386541
12,Orange,All other conditions,28.428094,All other conditions,25.685786,All other conditions,29.400387
13,Pitt,Stroke,29.739336,All other conditions,26.454446,Stroke,27.649326
14,Rowan,Nervous system disorder (excluding stroke),24.137931,Nervous system disorder (excluding stroke),34.090909,Nervous system disorder (excluding stroke),41.322314
15,Vance,Stroke,33.333333,All other conditions,35.294118,Stroke,34.591195
16,Wake,Stroke,29.516288,Stroke,29.098361,Stroke,29.260090

FInding which condition had the highest % by county across the years

In [62]:
max_conditions=[]

for _, row in Combined_highest_pct_condition.iterrows():
    # Get the three percent values
    p_2023 = row['Percent_Condition_x']
    p_2024 = row['Percent_Condition_y']
    p_2025 = row['Percent_Condition 2025']

    percents = {
        '2023': p_2023,
        '2024': p_2024,
        '2025': p_2025
    }

    max_year = max(percents, key=percents.get)
    
    # Get the corresponding condition
    if max_year == '2023':
        max_condition = row['Condition_x']
    elif max_year == '2024':
        max_condition = row['Condition_y']
    elif max_year =='2025':
        max_condition = row['Condition']
    
    # Append to list
    max_conditions.append(max_condition)

In [63]:
Combined_highest_pct_condition['Most Common Condition']=max_conditions
Combined_highest_pct_condition

C:\Users\vgcar\AppData\Local\Temp\ipykernel_32964\2253488663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Combined_highest_pct_condition['Most Common Condition']=max_conditions

,County/Parish,Condition_x,Percent_Condition_x,Condition_y,Percent_Condition_y,Condition,Percent_Condition 2025,Most Common Condition
0,Buncombe,Stroke,28.016878,All other conditions,26.140065,All other conditions,28.343146,All other conditions
1,Catawba,Stroke,44.910180,Stroke,29.508197,Stroke,37.321937,Stroke
2,Craven,Stroke,30.909091,Stroke,28.961749,All other conditions,27.459016,Stroke
3,Cumberland,Stroke,25.138632,Stroke,21.771218,"Hip or knee replacement, amputation or other b...",22.857143,Stroke
4,Durham,Stroke,27.737226,Stroke,25.937500,Stroke,31.347962,Stroke
5,Forsyth,Stroke,31.636864,Stroke,28.912467,Stroke,30.788027,Stroke
6,Guilford,Stroke,42.471591,Stroke,43.781726,Stroke,45.609436,Stroke
7,Lenoir,Stroke,46.153846,All other conditions,30.588235,All other conditions,31.683168,Stroke
8,Mecklenburg,Stroke,28.877962,Stroke,27.688400,Stroke,30.346232,Stroke
9,Moore,Stroke,44.262295,Stroke,41.954023,Stroke,49.696970,Stroke
10,Nash,Stroke,33.333333,Stroke,30.158730,Stroke,34.688347,Stroke
11,New Hanover,Stroke,37.261698,Stroke,30.906149,Stroke,27.386541,Stroke
12,Orange,All other conditions,28.428094,All other conditions,25.685786,All other conditions,29.400387,All other conditions
13,Pitt,Stroke,29.739336,All other conditions,26.454446,Stroke,27.649326,Stroke
14,Rowan,Nervous system disorder (excluding stroke),24.137931,Nervous system disorder (excluding stroke),34.090909,Nervous system disorder (excluding stroke),41.322314,Nervous system disorder (excluding stroke)
15,Vance,Stroke,33.333333,All other conditions,35.294118,Stroke,34.591195,All other conditions
16,Wake,Stroke,29.516288,Stroke,29.098361,Stroke,29.260090,Stroke

In [64]:
Combined_highest_pct_condition.to_csv('Combined_highest_pct_condition.csv')