In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Filtering down to NC Counties from 23-25:

In [2]:
IRF_provider_data_June_23 = pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Provider_Data_Jun2023.csv')
IRF_provider_data_June_23.head(1)

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,Phone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.436,-,07/01/2021,06/30/2022,-

In [3]:
NC_Readmissions_2023=IRF_provider_data_June_23.loc[(IRF_provider_data_June_23['Measure Code'] == 'I_018_01_PPR_WI_RSRR') & (IRF_provider_data_June_23['State']=='NC')].reset_index(drop=True)
NC_Readmissions_2023.head()

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,Phone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,343025,CAREPARTNERS REHABILITATION HOSP,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,I_018_01_PPR_WI_RSRR,4.34,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
1,343026,CAROLINAS REHABILITATION,1100 BLYTHE BOULEVARD,-,CHARLOTTE,NC,28203,Mecklenburg,(704) 355-4370,4,I_018_01_PPR_WI_RSRR,3.13,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
2,343027,NOVANT HEALTH REHABILITATION HOSPITAL,2475 HILLCREST CENTER CIRCLE,-,WINSTON-SALEM,NC,27103,Forsyth,(336) 754-3500,4,I_018_01_PPR_WI_RSRR,5.04,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
3,34T004,HIGH POINT REGIONAL HOSPITAL,601 N ELM ST,-,HIGH POINT,NC,27262,Guilford,(336) 878-6442,4,I_018_01_PPR_WI_RSRR,3.95,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
4,34T008,CENTER FOR INPATIENT REHAB,500 LAUCHWOOD DR,-,LAURINBURG,NC,28352,Scotland,(910) 291-7327,4,I_018_01_PPR_WI_RSRR,4.28,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
5,34T014,WHITAKER REHABILITATION CENTER,3333 SILAS CREEK PARKWAY,-,WINSTON SALEM,NC,27103,Forsyth,(336) 718-1629,4,I_018_01_PPR_WI_RSRR,Not Available,5,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
6,34T015,ROWAN REGIONAL MEDICAL CENTER,612 MOCKSVILLE AVENUE,-,SALISBURY,NC,28114,Rowan,(704) 210-5308,4,I_018_01_PPR_WI_RSRR,3.68,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
7,34T027,LENOIR MEMORIAL HOSPITAL REHAB UNIT,100 AIRPORT RD,-,KINSTON,NC,28501,Lenoir,(252) 522-7772,4,I_018_01_PPR_WI_RSRR,3.78,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
8,34T028,CAPE FEAR VALLEY REHABILITATION CENTER,1638 OWEN DRIVE,-,FAYETTEVILLE,NC,28302,Cumberland,(910) 615-6843,4,I_018_01_PPR_WI_RSRR,3.80,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
9,34T040,PITT COUNTY MEMORIAL HOSPITAL,PO BOX 8447,-,GREENVILLE,NC,27835,Pitt,(252) 847-0873,4,I_018_01_PPR_WI_RSRR,3.92,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
10,34T047,NORTH CAROLINA BAPTIST HOSPITALS,MEDICAL CENTER BLVD,-,WINSTON SALEM,NC,27157,Forsyth,(336) 713-8328,4,I_018_01_PPR_WI_RSRR,4.11,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
11,34T061,UNC HOSPITALS INPATIENT REHAB,101 MANNING DR,-,CHAPEL HILL,NC,27514,Orange,(919) 984-5306,4,I_018_01_PPR_WI_RSRR,4.53,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
12,34T069,WAKEMED REHAB,3000 NEW BERN AVE.,-,RALEIGH,NC,27610,Wake,(919) 350-8864,4,I_018_01_PPR_WI_RSRR,3.34,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
13,34T091,MOSES H. CONE MEMORIAL HOSPITAL,1200 NORTH ELM STREET,-,GREENSBORO,NC,27401,Guilford,(336) 832-7000,4,I_018_01_PPR_WI_RSRR,3.58,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
14,34T097,REGIONAL REHAB CENTER AT HUGH CHATHAM,700 JOHNSON RIDGE ROAD,-,ELKIN,NC,28621,Surry,(336) 527-7052,4,I_018_01_PPR_WI_RSRR,Not Available,5,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
15,34T098,CAROLINAS MEDICAL CENTER - PINEVILLE REHABILIT...,10628 PARK ROAD,-,CHARLOTTE,NC,28210,Mecklenburg,(704) 355-4602,4,I_018_01_PPR_WI_RSRR,3.32,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
16,34T113,CAROLINAS MEDICAL CENTER,1000 BLYTHE BLVD,-,CHARLOTTE,NC,28203,Mecklenburg,(704) 355-4602,4,I_018_01_PPR_WI_RSRR,Not Available,5,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
17,34T115,FIRSTHEALTH MOORE REGIONAL HOSPITAL,155 MEMORIAL DRIVE,-,PINEHURST,NC,28374,Moore,(910) 715-1000,4,I_018_01_PPR_WI_RSRR,3.59,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
18,34T116,DLP FRYE REGIONAL MEDICAL CENTER,420 N CENTER ST,REHAB SERVICES,HICKORY,NC,28601,Catawba,(828) 315-3602,4,I_018_01_PPR_WI_RSRR,4.87,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
19,34T131,CAROLINAEAST REHABILITATION HOSPITAL,2000 NEUSE BLVD.,-,NEW BERN,NC,28561,Craven,(252) 634-6001,4,I_018_01_PPR_WI_RSRR,3.86,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
20,34T132,MARIA PARHAM HEALTHCARE ASSOCIATION INC,566 RUIN CREEK RD,-,HENDERSON,NC,27536,Vance,(252) 436-1166,4,I_018_01_PPR_WI_RSRR,4.52,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
21,34T141,NEW HANOVER REGIONAL MEDICAL CENTER REHABILITA...,2131 SOUTH 17TH STREET,-,WILMINGTON,NC,28402,New Hanover,(910) 667-5619,4,I_018_01_PPR_WI_RSRR,3.75,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
22,34T143,CATAWBA VALLEY MEDICAL CENTER,810 FAIRGROVE CHURCH RD,-,HICKORY,NC,28602,Catawba,(828) 326-3248,4,I_018_01_PPR_WI_RSRR,4.00,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
23,34T147,BRYANT T. ALDRIDGE REHABILITATION CENTER,2400 MEDPARK DRIVE,-,ROCKY MOUNT,NC,27804,Nash,(252) 962-3709,4,I_018_01_PPR_WI_RSRR,4.06,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021
24,34T155,DURHAM REGIONAL HOSPITAL,3643 N ROXBORO ROAD,BOX 52,DURHAM,NC,27704,Durham,(919) 470-7226,4,I_018_01_PPR_WI_RSRR,4.46,-,07/01/2019,06/30/2021,07/01/2019 - 12/31/2019; 07/01/2020 - 06/30/2021

In [4]:
drop_rows= NC_Readmissions_2023.loc[NC_Readmissions_2023["Score"]== "Not Available"]

In [5]:
NC_Readmissions_2023=NC_Readmissions_2023.drop(drop_rows.index, axis=0)

In [6]:
NC_Readmissions_2023['Score']=NC_Readmissions_2023['Score'].astype(float).reset_index(drop=True)

In [7]:
NC_Readmissions_2023=NC_Readmissions_2023[['CMS Certification Number (CCN)', 'County Name','State','Measure Code','Score']].rename(columns={'Score':'2023 Score','County Name':'County/Parish'})

In [8]:
Avg_NC_Readmissions_2023=NC_Readmissions_2023.groupby('County/Parish')['2023 Score'].mean().to_frame()

In [9]:
Avg_NC_Readmissions_2023=Avg_NC_Readmissions_2023.reset_index()
Avg_NC_Readmissions_2023

   County/Parish  2023 Score
0       Buncombe       4.340
1        Catawba       3.750
2         Craven       4.000
3     Cumberland       3.920
4         Durham         NaN
5        Forsyth       4.785
6       Guilford       3.635
7         Lenoir       3.800
8    Mecklenburg       4.000
9          Moore       4.520
10          Nash         NaN
11   New Hanover       4.460
12        Orange       3.340
13          Pitt       4.110
14         Rowan       3.780
15      Scotland       4.280
16         Vance       4.060
17          Wake       3.580

In [10]:
IRF_provider_data_June_24 = pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Provider_Data_Jun2024.csv')
IRF_provider_data_June_24.head(1)

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.773,-,07/01/2022,06/30/2023,-

In [11]:
NC_Readmissions_2024=IRF_provider_data_June_24.loc[(IRF_provider_data_June_24['Measure Code'] == 'I_018_01_PPR_WI_RSRR')& (IRF_provider_data_June_24['State']=='NC')].reset_index(drop=True)

In [12]:
drop_rows= NC_Readmissions_2024.loc[NC_Readmissions_2024["Score"]== "Not Available"]

In [13]:
NC_Readmissions_2024=NC_Readmissions_2024.drop(drop_rows.index, axis=0)

In [14]:
NC_Readmissions_2024['Score']=NC_Readmissions_2024['Score'].astype(float)

In [15]:
NC_Readmissions_2024=NC_Readmissions_2024[['CMS Certification Number (CCN)', 'County/Parish','State','Measure Code','Score']].rename(columns={'Score':'2024 Score'})

In [16]:
NC_Avg_Readmissions_2024=NC_Readmissions_2024.groupby('County/Parish')['2024 Score'].mean().to_frame().reset_index()
NC_Avg_Readmissions_2024

   County/Parish  2024 Score
0       Buncombe       4.920
1        Catawba       5.075
2         Craven       4.730
3     Cumberland       5.990
4         Durham       4.760
5        Forsyth       5.550
6       Guilford       4.655
7         Lenoir       4.280
8    Mecklenburg       3.545
9          Moore       4.980
10          Nash       3.950
11   New Hanover       4.230
12        Orange       3.740
13          Pitt       5.860
14         Rowan       5.330
15         Vance       4.130
16          Wake       3.250

In [17]:
IRF_provider_data_June_25 = pd.read_csv('../data/Inpatient_Rehabilitation_Facility_Provider_Data_Jun2025.csv')

In [18]:
NC_Readmissions_2025=IRF_provider_data_June_25.loc[(IRF_provider_data_June_25['Measure Code'] == 'I_018_01_PPR_WI_RSRR')& (IRF_provider_data_June_25['State']=='NC')].reset_index(drop=True)

In [19]:
drop_rows= NC_Readmissions_2025.loc[NC_Readmissions_2025["Score"]== "Not Available"]

In [20]:
NC_Readmissions_2025=NC_Readmissions_2025.drop(drop_rows.index, axis=0)

In [21]:
NC_Readmissions_2025['Score']=NC_Readmissions_2025['Score'].astype(float)

In [22]:
NC_Readmissions_2025=NC_Readmissions_2025[['CMS Certification Number (CCN)', 'County/Parish','State','Measure Code','Score']].rename(columns={'Score':'2025 Score'})

In [23]:
Avg_NC_Readmissions_2025=NC_Readmissions_2025.groupby('County/Parish')['2025 Score'].mean().to_frame().reset_index()
Avg_NC_Readmissions_2025

   County/Parish  2025 Score
0       Buncombe       4.940
1        Catawba       5.240
2         Craven       5.070
3     Cumberland       5.030
4         Durham       3.910
5        Forsyth       4.505
6       Guilford       4.170
7         Lenoir       4.800
8    Mecklenburg       3.940
9          Moore       4.090
10          Nash       3.430
11   New Hanover       3.860
12        Orange       3.710
13          Pitt       6.400
14         Rowan       4.550
15         Vance       4.000
16          Wake       3.360

Merging all the frames together:

In [24]:
dfs=[Avg_NC_Readmissions_2023, NC_Avg_Readmissions_2024, Avg_NC_Readmissions_2025]

Avg_NC_Readmits_Merged = dfs[0]

for i in range(1, len(dfs)):
    Avg_NC_Readmits_Merged= pd.merge(Avg_NC_Readmits_Merged, dfs[i], on = 'County/Parish', how ='inner')


Avg_NC_Readmits_Merged

   County/Parish  2023 Score  2024 Score  2025 Score
0       Buncombe       4.340       4.920       4.940
1        Catawba       3.750       5.075       5.240
2         Craven       4.000       4.730       5.070
3     Cumberland       3.920       5.990       5.030
4         Durham         NaN       4.760       3.910
5        Forsyth       4.785       5.550       4.505
6       Guilford       3.635       4.655       4.170
7         Lenoir       3.800       4.280       4.800
8    Mecklenburg       4.000       3.545       3.940
9          Moore       4.520       4.980       4.090
10          Nash         NaN       3.950       3.430
11   New Hanover       4.460       4.230       3.860
12        Orange       3.340       3.740       3.710
13          Pitt       4.110       5.860       6.400
14         Rowan       3.780       5.330       4.550
15         Vance       4.060       4.130       4.000
16          Wake       3.580       3.250       3.360

In [25]:
Avg_NC_Readmits_Merged['County Overall Avg Readmit Rate']= Avg_NC_Readmits_Merged[['2023 Score','2024 Score','2025 Score']].mean(axis=1)
Avg_NC_Readmits_Merged

,County/Parish,2023 Score,2024 Score,2025 Score,County Overall Avg Readmit Rate
0,Buncombe,4.340,4.920,4.940,4.733333
1,Catawba,3.750,5.075,5.240,4.688333
2,Craven,4.000,4.730,5.070,4.600000
3,Cumberland,3.920,5.990,5.030,4.980000
4,Durham,NaN,4.760,3.910,4.335000
5,Forsyth,4.785,5.550,4.505,4.946667
6,Guilford,3.635,4.655,4.170,4.153333
7,Lenoir,3.800,4.280,4.800,4.293333
8,Mecklenburg,4.000,3.545,3.940,3.828333
9,Moore,4.520,4.980,4.090,4.530000
10,Nash,NaN,3.950,3.430,3.690000
11,New Hanover,4.460,4.230,3.860,4.183333
12,Orange,3.340,3.740,3.710,3.596667
13,Pitt,4.110,5.860,6.400,5.456667
14,Rowan,3.780,5.330,4.550,4.553333
15,Vance,4.060,4.130,4.000,4.063333
16,Wake,3.580,3.250,3.360,3.396667

In [26]:
Avg_NC_Readmits_Merged.columns

Index(['County/Parish', '2023 Score', '2024 Score', '2025 Score',
       'County Overall Avg Readmit Rate'],
      dtype='object')

In [27]:
Avg_NC_Readmits_Merged=Avg_NC_Readmits_Merged.sort_values(by='County Overall Avg Readmit Rate', ascending= False)

In [28]:
Avg_NC_Readmits_Merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 13 to 16
Data columns (total 5 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   County/Parish                    17 non-null     object
 1   2023 Score                       15 non-null     float64
 2   2024 Score                       17 non-null     float64
 3   2025 Score                       17 non-null     float64
 4   County Overall Avg Readmit Rate  17 non-null     float64
dtypes: float64(4), object(1)
memory usage: 816.0+ bytes

In [29]:
percent_change=[]

for index, row in Avg_NC_Readmits_Merged.iterrows():
    start= row['2023 Score']
    end= row['2025 Score']
    pct_change=((end-start)/start) *100
    percent_change.append(pct_change)

In [30]:
Avg_NC_Readmits_Merged['Pct Change']=percent_change
Avg_NC_Readmits_Merged

,County/Parish,2023 Score,2024 Score,2025 Score,County Overall Avg Readmit Rate,Pct Change
13,Pitt,4.110,5.860,6.400,5.456667,55.717762
3,Cumberland,3.920,5.990,5.030,4.980000,28.316327
5,Forsyth,4.785,5.550,4.505,4.946667,-5.851620
0,Buncombe,4.340,4.920,4.940,4.733333,13.824885
1,Catawba,3.750,5.075,5.240,4.688333,39.733333
2,Craven,4.000,4.730,5.070,4.600000,26.750000
14,Rowan,3.780,5.330,4.550,4.553333,20.370370
9,Moore,4.520,4.980,4.090,4.530000,-9.513274
4,Durham,NaN,4.760,3.910,4.335000,NaN
7,Lenoir,3.800,4.280,4.800,4.293333,26.315789
11,New Hanover,4.460,4.230,3.860,4.183333,-13.452915
6,Guilford,3.635,4.655,4.170,4.153333,14.718019
15,Vance,4.060,4.130,4.000,4.063333,-1.477833
8,Mecklenburg,4.000,3.545,3.940,3.828333,-1.500000
10,Nash,NaN,3.950,3.430,3.690000,NaN
12,Orange,3.340,3.740,3.710,3.596667,11.077844
16,Wake,3.580,3.250,3.360,3.396667,-6.145251

In [31]:
Avg_NC_Readmits_Merged.head(3)

,County/Parish,2023 Score,2024 Score,2025 Score,County Overall Avg Readmit Rate,Pct Change
13,Pitt,4.110,5.86,6.400,5.456667,55.717762
3,Cumberland,3.920,5.99,5.030,4.980000,28.316327
5,Forsyth,4.785,5.55,4.505,4.946667,-5.851620

In [32]:
Avg_NC_Readmits_Merged.tail(3)

,County/Parish,2023 Score,2024 Score,2025 Score,County Overall Avg Readmit Rate,Pct Change
10,Nash,NaN,3.95,3.43,3.690000,NaN
12,Orange,3.34,3.74,3.71,3.596667,11.077844
16,Wake,3.58,3.25,3.36,3.396667,-6.145251

Save to CSV:

In [33]:
Avg_NC_Readmits_Merged.to_csv('Avg_NC_Readmits_Merged.csv', index=False)

In [34]:
NC_Overall_Readmit_Avg= Avg_NC_Readmits_Merged[['2023 Score','2024 Score', '2025 Score']].mean()
NC_Overall_Readmit_Avg

2023 Score    4.005333
2024 Score    4.645588
2025 Score    4.412059
dtype: float64

In [35]:
NC_Overall_Readmit_Avg=NC_Overall_Readmit_Avg.to_frame()
NC_Overall_Readmit_Avg

                   0
2023 Score  4.005333
2024 Score  4.645588
2025 Score  4.412059

In [36]:
NC_Overall_Readmit_Avg=NC_Overall_Readmit_Avg.transpose()
NC_Overall_Readmit_Avg

   2023 Score  2024 Score  2025 Score
0    4.005333    4.645588    4.412059

In [37]:
NC_Overall_Readmit_Avg.to_csv('NC_Overall_Readmit_Avg.csv', index=True)

### Bringing in National Data now:

In [38]:
National_Readmit_Avg_25= pd.read_csv('../data/Inpatient_Rehabilitation_Facility_National_Data_Jun2025.csv')

In [39]:
National_Readmit_Avg_25= National_Readmit_Avg_25.loc[National_Readmit_Avg_25['Measure Code']=='I_018_01_PPR_WI_NATL_OBS_RATE'].rename(columns={'Score':'2025 Score'})

In [40]:
National_Readmit_Avg_25=National_Readmit_Avg_25[['Measure Code','2025 Score']]

In [41]:
National_Readmit_Avg_25['2025 Score']=National_Readmit_Avg_25['2025 Score'].astype(str).astype(float)

In [42]:
National_Readmit_Avg_25

                     Measure Code  2025 Score
11  I_018_01_PPR_WI_NATL_OBS_RATE        4.75

In [43]:
National_Readmit_Avg_24= pd.read_csv('../data/Inpatient_Rehabilitation_Facility-National_Data_Jun2024.csv')

In [44]:
National_Readmit_Avg_24=National_Readmit_Avg_24.loc[National_Readmit_Avg_24['Measure Code']=='I_018_01_PPR_WI_NATL_OBS_RATE'].rename(columns={'Score':'2024 Score'})

In [45]:
National_Readmit_Avg_24=National_Readmit_Avg_24[['Measure Code','2024 Score']]

In [46]:
National_Readmit_Avg_24['2024 Score']=National_Readmit_Avg_24['2024 Score'].astype(str).astype(float)
National_Readmit_Avg_24

                     Measure Code  2024 Score
14  I_018_01_PPR_WI_NATL_OBS_RATE        4.89

In [47]:
National_Readmit_Avg_23= pd.read_csv('../data/Inpatient_Rehabilitation_Facility-National_Data_Jun2023.csv')

In [48]:
National_Readmit_Avg_23=National_Readmit_Avg_23.loc[National_Readmit_Avg_23['Measure Code']=='I_018_01_PPR_WI_NATL_OBS_RATE'].rename(columns={'Score':'2023 Score'})

In [49]:
National_Readmit_Avg_23=National_Readmit_Avg_23[['Measure Code', '2023 Score']]

In [50]:
National_Readmit_Avg_23['2023 Score']=National_Readmit_Avg_23['2023 Score'].astype(str).astype(float)
National_Readmit_Avg_23

                     Measure Code  2023 Score
14  I_018_01_PPR_WI_NATL_OBS_RATE        4.24

Combining the National Data togehter

In [51]:
dfs=[National_Readmit_Avg_23, National_Readmit_Avg_24, National_Readmit_Avg_25]

National_Readmit_Rate_Combined = dfs[0]

for i in range(1, len(dfs)):
    National_Readmit_Rate_Combined= pd.merge(National_Readmit_Rate_Combined, dfs[i], on = 'Measure Code', how ='inner')


National_Readmit_Rate_Combined

                    Measure Code  2023 Score  2024 Score  2025 Score
0  I_018_01_PPR_WI_NATL_OBS_RATE        4.24        4.89        4.75

In [52]:
National_Readmit_Rate_Combined.to_csv('National_Readmit_Rate_Combined.csv',index=False)

In [53]:
National_Readmit_Rate_Combined['Overall Avg']=National_Readmit_Rate_Combined[['2023 Score','2024 Score','2025 Score']].mean(axis=1)
National_Readmit_Rate_Combined

,Measure Code,2023 Score,2024 Score,2025 Score,Overall Avg
0,I_018_01_PPR_WI_NATL_OBS_RATE,4.24,4.89,4.75,4.626667

In [54]:
National_Readmit_Rate_Combined.to_csv('National_Readmit_Rate_Combined.csv', index=False)

In [55]:
National_Readmit_Rate_Combined_fix=National_Readmit_Rate_Combined.drop(columns=['Measure Code','Overall Avg'])
National_Readmit_Rate_Combined_fix

   2023 Score  2024 Score  2025 Score
0        4.24        4.89        4.75

In [56]:
National_Readmit_Rate_Combined_fix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   2023 Score  1 non-null      float64
 1   2024 Score  1 non-null      float64
 2   2025 Score  1 non-null      float64
dtypes: float64(3)
memory usage: 156.0 bytes

In [57]:
NC_and_National_readmit_overall_avgs= pd.concat([National_Readmit_Rate_Combined_fix,NC_Overall_Readmit_Avg])
NC_and_National_readmit_overall_avgs

   2023 Score  2024 Score  2025 Score
0    4.240000    4.890000    4.750000
0    4.005333    4.645588    4.412059

#### Merging readmission rates with region/ownership type data

In [58]:
Region_Ownership_Type=pd.read_csv('../data/Region_Ownership_Type.csv')
Region_Ownership_Type.head(1)

   Unnamed: 0 Ownership Type   County                  Region
0           0     For profit  Catawba  Western North Carolina

In [59]:
Avg_NC_Readmits_Merged.head(1)

,County/Parish,2023 Score,2024 Score,2025 Score,County Overall Avg Readmit Rate,Pct Change
13,Pitt,4.11,5.86,6.4,5.456667,55.717762

In [60]:
Region_Ownership_Type=Region_Ownership_Type.rename(columns={'County':'County/Parish'})

In [62]:
Readmits_Region_Ownership_type= pd.merge(Region_Ownership_Type, Avg_NC_Readmits_Merged,
                                         on='County/Parish',
                                         how='inner')
Readmits_Region_Ownership_type.head()

,Unnamed: 0,Ownership Type,County/Parish,Region,2023 Score,2024 Score,2025 Score,County Overall Avg Readmit Rate,Pct Change
0,0,For profit,Catawba,Western North Carolina,3.750,5.075,5.240,4.688333,39.733333
1,1,For profit,Forsyth,Central North Carolina,4.785,5.550,4.505,4.946667,-5.851620
2,2,For profit,Vance,Central North Carolina,4.060,4.130,4.000,4.063333,-1.477833
3,3,Government,Mecklenburg,Central North Carolina,4.000,3.545,3.940,3.828333,-1.500000
4,4,Government,Craven,Eastern North Carolina,4.000,4.730,5.070,4.600000,26.750000

In [63]:
Readmits_Region_Ownership_type=Readmits_Region_Ownership_type[['Ownership Type','County/Parish','Region','Pct Change']]
Readmits_Region_Ownership_type.head(3)

  Ownership Type County/Parish                  Region  Pct Change
0     For profit       Catawba  Western North Carolina   39.733333
1     For profit       Forsyth  Central North Carolina   -5.851620
2     For profit         Vance  Central North Carolina   -1.477833

In [64]:
Readmits_Region_Ownership_type=Readmits_Region_Ownership_type.rename(columns={'Pct Change':'Pct Change Redmission Score'})
Readmits_Region_Ownership_type

,Ownership Type,County/Parish,Region,Pct Change Redmission Score
0,For profit,Catawba,Western North Carolina,39.733333
1,For profit,Forsyth,Central North Carolina,-5.851620
2,For profit,Vance,Central North Carolina,-1.477833
3,Government,Mecklenburg,Central North Carolina,-1.500000
4,Government,Craven,Eastern North Carolina,26.750000
5,Government,Durham,Central North Carolina,NaN
6,Government,Nash,Eastern North Carolina,NaN
7,Government,Orange,Central North Carolina,11.077844
8,Non-profit,Forsyth,Central North Carolina,-5.851620
9,Non-profit,Guilford,Central North Carolina,14.718019
10,Non-profit,Buncombe,Western North Carolina,13.824885
11,Non-profit,Catawba,Western North Carolina,39.733333
12,Non-profit,Cumberland,Eastern North Carolina,28.316327
13,Non-profit,Lenoir,Eastern North Carolina,26.315789
14,Non-profit,Mecklenburg,Central North Carolina,-1.500000
15,Non-profit,Moore,Central North Carolina,-9.513274
16,Non-profit,Pitt,Eastern North Carolina,55.717762
17,Non-profit,Rowan,Central North Carolina,20.370370
18,Non-profit,Wake,Central North Carolina,-6.145251