In [1]:
import pandas as pd

In [2]:
race_age_groups_23=pd.read_csv('../data/Race_Age_Groups_23_CSV.csv')

In [3]:
race_age_groups_24=pd.read_csv('../data/Race_Age_Groups_24_CSV.csv')

In [4]:
race_age_groups_25=pd.read_csv('../data/Race_Age_Groups_25_CSV.csv')

In [5]:
race_age_groups_23.head(3)

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37019,Brunswick,Eastern North Carolina,Cape Fear Council of Governments,Wilmington,2023.0,Other,1.0,269.0,156.0,...,47.91,1448.0,395.0,881.0,1317.0,1684.0,"{""coordinates"":[[[[-78.16235,34.357006999],[-7...",NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"34.120""",Estimate,2023,"34.03887554891685, -78.22740741677175",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
race_age_groups_23.columns

Index(['fips', 'County', 'Region', 'COG', 'MSA', 'Year', 'Race', 'Group N',
       'Age 0 to 2', 'Age 3 to 4', 'Age 5', 'Age 6 to 9', 'Age 10 to 13',
       'Age 14', 'Age 15', 'Age 16 to 17', 'Age 18 to 19', 'Age 20 to 24',
       'Age 25 to 34', 'Age 35 to 44', 'Age 45 to 54', 'Age 55 to 59',
       'Age 60 to 64', 'Age 65 to 74', 'Age 75 to 84', 'Age 85 to 99',
       'Age 100', 'Total', 'medage', 'Age 0 to 17', 'Age 18 to 24',
       'Age 25 to 44', 'Age 45 to 64', 'Age 65 Plus', 'geom',
       'Estimate/Projection', 'Vintage', 'geo_point_2d'],
      dtype='object')

In [7]:
region_NC_23=race_age_groups_23[['County','Region','Age 65 Plus','Total','Year']]
region_NC_23

        County                  Region  Age 65 Plus    Total    Year
0    Brunswick  Eastern North Carolina       1684.0   5725.0  2023.0
1          NaN                     NaN          NaN      NaN     NaN
2      34.120"                Estimate          NaN      NaN     NaN
3     Cabarrus  Central North Carolina        614.0  11327.0  2023.0
4     Alamance  Central North Carolina       6115.0  38581.0  2023.0
..         ...                     ...          ...      ...     ...
816      Macon  Western North Carolina      10791.0  35524.0  2023.0
817        NaN                     NaN          NaN      NaN     NaN
818   Estimate                    2023          NaN      NaN     NaN
819    Tyrrell  Eastern North Carolina        614.0   2225.0  2023.0
820      Surry  Western North Carolina        530.0   2867.0  2023.0

[821 rows x 5 columns]

In [8]:
NC_IRF_Counties_List=['Buncombe','Catawba','Craven','Cumberland','Durham','Forsyth','Guilford','Lenoir','Mecklenburg','Moore','Nash','New_Hanover','Orange','Pitt','Rowan','Vance','Wake']

In [9]:
region_NC_23= region_NC_23[region_NC_23['County'].isin(NC_IRF_Counties_List)]
region_NC_23

       County                  Region  Age 65 Plus     Total    Year
21    Catawba  Western North Carolina       1091.0    7825.0  2023.0
31     Craven  Eastern North Carolina        679.0    3802.0  2023.0
67   Guilford  Central North Carolina       3123.0   32699.0  2023.0
79   Buncombe  Western North Carolina      54841.0  241346.0  2023.0
98   Buncombe  Western North Carolina       2797.0   16517.0  2023.0
..        ...                     ...          ...       ...     ...
744  Guilford  Central North Carolina       1054.0   22430.0  2023.0
747   Forsyth  Central North Carolina       1133.0   11241.0  2023.0
748     Rowan  Central North Carolina      22785.0  117253.0  2023.0
755   Forsyth  Central North Carolina      52299.0  259712.0  2023.0
770    Durham  Central North Carolina      29830.0  182995.0  2023.0

[80 rows x 5 columns]

In [10]:
region_NC_23['Pct 65 plus']= (region_NC_23['Age 65 Plus']/region_NC_23['Total']) * 100
region_NC_23

C:\Users\vgcar\AppData\Local\Temp\ipykernel_38376\4113607466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  region_NC_23['Pct 65 plus']= (region_NC_23['Age 65 Plus']/region_NC_23['Total']) * 100

,County,Region,Age 65 Plus,Total,Year,Pct 65 plus
21,Catawba,Western North Carolina,1091.0,7825.0,2023.0,13.942492
31,Craven,Eastern North Carolina,679.0,3802.0,2023.0,17.859022
67,Guilford,Central North Carolina,3123.0,32699.0,2023.0,9.550751
79,Buncombe,Western North Carolina,54841.0,241346.0,2023.0,22.722979
98,Buncombe,Western North Carolina,2797.0,16517.0,2023.0,16.934068
...,...,...,...,...,...,...
744,Guilford,Central North Carolina,1054.0,22430.0,2023.0,4.699064
747,Forsyth,Central North Carolina,1133.0,11241.0,2023.0,10.079174
748,Rowan,Central North Carolina,22785.0,117253.0,2023.0,19.432339
755,Forsyth,Central North Carolina,52299.0,259712.0,2023.0,20.137306
770,Durham,Central North Carolina,29830.0,182995.0,2023.0,16.300992

In [11]:
region_NC_23_totalpop=region_NC_23.groupby('Region')['Total'].sum()
region_NC_23_totalpop

Region
Central North Carolina    4090082.0
Eastern North Carolina     768185.0
Western North Carolina     443243.0
Name: Total, dtype: float64

In [12]:
region_NC_23_totalpop=region_NC_23_totalpop.to_frame()
region_NC_23_totalpop

                            Total
Region
Central North Carolina  4090082.0
Eastern North Carolina   768185.0
Western North Carolina   443243.0

In [13]:
region_NC_23_pct65= region_NC_23.groupby('Region')['Age 65 Plus'].sum().to_frame()
region_NC_23_pct65

                        Age 65 Plus
Region
Central North Carolina     597310.0
Eastern North Carolina     124416.0
Western North Carolina      92030.0

In [14]:
region_NC_23_pct65=region_NC_23_pct65.rename(columns={'Age 65 Plus':'Age 65 Plus 2023'})
region_NC_23_pct65

                        Age 65 Plus 2023
Region
Central North Carolina          597310.0
Eastern North Carolina          124416.0
Western North Carolina           92030.0

In [15]:
pct_65plus_by_region_23=pd.merge(region_NC_23_pct65, region_NC_23_totalpop,
                      on='Region',
                      how='inner')
pct_65plus_by_region_23

                        Age 65 Plus 2023      Total
Region
Central North Carolina          597310.0  4090082.0
Eastern North Carolina          124416.0   768185.0
Western North Carolina           92030.0   443243.0

In [16]:
pct_65plus_by_region_23['pct 65 plus']=(pct_65plus_by_region_23['Age 65 Plus 2023'])/(pct_65plus_by_region_23['Total']) * 100
pct_65plus_by_region_23

                        Age 65 Plus 2023      Total  pct 65 plus
Region
Central North Carolina          597310.0  4090082.0    14.603864
Eastern North Carolina          124416.0   768185.0    16.196099
Western North Carolina           92030.0   443243.0    20.762877

In [17]:
pct_65plus_by_region_23.to_csv('pct_65plus_by_region_23.csv', index=True)

In [18]:
race_age_groups_25

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37003,Alexander,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2025.0,Asian & Pacific Islander,1.0,17.0,12.0,...,34.272727,100.0,38.0,171.0,94.0,35.0,"{""coordinates"":[[[[-81.328324,35.996582999],[-...",Projection,2024.0,"35.921026310411975, -81.17702681231853"
1,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2025.0,Other,1.0,690.0,444.0,...,17.453125,4449.0,1080.0,1997.0,942.0,220.0,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Projection,2024.0,"36.04370973725824, -79.39942485544303"
2,37023,Burke,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2025.0,Black,1.0,123.0,91.0,...,36.940299,1190.0,723.0,1001.0,1317.0,953.0,"{""coordinates"":[[[[-81.943188,35.960049999],[-...",NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,149,"35.""",Projection,2024,"35.74961065992926, -81.70477863312823",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,37147,Pitt,Eastern North Carolina,Mid-East Commission,Greenville,2025.0,Black,1.0,2643.0,1755.0,...,34.071379,15643.0,8437.0,20297.0,12946.0,8576.0,"{""coordinates"":[[[[-77.700692,35.652294999],[-...",NaN,NaN,NaN
825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
826,7,"35.50""",Projection,2024,"35.59329885449204, -77.37449649585241",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
827,37183,Wake,Central North Carolina,Central Pines Regional Council,Raleigh-Cary,2025.0,Asian & Pacific Islander,1.0,3425.0,2093.0,...,39.725061,23218.0,12272.0,41271.0,37225.0,12371.0,"{""coordinates"":[[[[-78.751273,36.070833999],[-...",Projection,2024.0,"35.79031331872891, -78.65028009124825"
828,37159,Rowan,Central North Carolina,Centralina Council of Governments,Charlotte-Concord-Gastonia (NC),2025.0,Black,1.0,819.0,581.0,...,36.307317,5868.0,2606.0,7169.0,5880.0,3659.0,"{""coordinates"":[[[[-80.707824,35.852960999],[-...",Projection,2024.0,"35.63942562816136, -80.52474972960941"

In [19]:
region_NC_25=race_age_groups_25[['County','Region','Age 65 Plus','Total']]
region_NC_25

        County                  Region  Age 65 Plus     Total
0    Alexander  Western North Carolina         35.0     438.0
1     Alamance  Central North Carolina        220.0    8688.0
2        Burke  Western North Carolina        953.0    5184.0
3          NaN                     NaN          NaN       NaN
4         35."              Projection          NaN       NaN
..         ...                     ...          ...       ...
824       Pitt  Eastern North Carolina       8576.0   65899.0
825        NaN                     NaN          NaN       NaN
826     35.50"              Projection          NaN       NaN
827       Wake  Central North Carolina      12371.0  126357.0
828      Rowan  Central North Carolina       3659.0   25182.0

[829 rows x 4 columns]

In [20]:
region_NC_25= region_NC_25[region_NC_25['County'].isin(NC_IRF_Counties_List)]
region_NC_25

         County                  Region  Age 65 Plus     Total
19   Cumberland  Eastern North Carolina      25406.0  161147.0
40       Lenoir  Eastern North Carolina       7133.0   29126.0
43      Forsyth  Central North Carolina        490.0   17861.0
59   Cumberland  Eastern North Carolina        818.0    7080.0
73     Buncombe  Western North Carolina      57666.0  245397.0
..          ...                     ...          ...       ...
780      Durham  Central North Carolina       2115.0   19899.0
781       Vance  Central North Carolina         57.0    1312.0
824        Pitt  Eastern North Carolina       8576.0   65899.0
827        Wake  Central North Carolina      12371.0  126357.0
828       Rowan  Central North Carolina       3659.0   25182.0

[80 rows x 4 columns]

In [21]:
region_NC_25_totalpop=region_NC_25.groupby('Region')['Total'].sum().to_frame()
region_NC_25_totalpop

                            Total
Region
Central North Carolina  4202985.0
Eastern North Carolina   770585.0
Western North Carolina   452938.0

In [22]:
region_NC_25_pct65= region_NC_23.groupby('Region')['Age 65 Plus'].sum().to_frame()
region_NC_25_pct65

                        Age 65 Plus
Region
Central North Carolina     597310.0
Eastern North Carolina     124416.0
Western North Carolina      92030.0

In [23]:
region_NC_25_pct65=region_NC_25_pct65.rename(columns={'Age 65 Plus':'Age 65 Plus 2025'})
region_NC_25_pct65

                        Age 65 Plus 2025
Region
Central North Carolina          597310.0
Eastern North Carolina          124416.0
Western North Carolina           92030.0

In [24]:
pct65plus_region_25=pd.merge(region_NC_25_totalpop,region_NC_25_pct65,
                             on='Region',
                             how= 'inner')
pct65plus_region_25

                            Total  Age 65 Plus 2025
Region
Central North Carolina  4202985.0          597310.0
Eastern North Carolina   770585.0          124416.0
Western North Carolina   452938.0           92030.0

In [25]:
pct65plus_region_25['pct 65 plus']= (pct65plus_region_25['Age 65 Plus 2025']/pct65plus_region_25['Total']) * 100
pct65plus_region_25

                            Total  Age 65 Plus 2025  pct 65 plus
Region
Central North Carolina  4202985.0          597310.0    14.211566
Eastern North Carolina   770585.0          124416.0    16.145656
Western North Carolina   452938.0           92030.0    20.318454

In [26]:
pct65plus_region_25=pct65plus_region_25.reset_index()
pct65plus_region_25

                   Region      Total  Age 65 Plus 2025  pct 65 plus
0  Central North Carolina  4202985.0          597310.0    14.211566
1  Eastern North Carolina   770585.0          124416.0    16.145656
2  Western North Carolina   452938.0           92030.0    20.318454

In [27]:
pct65plus_region_25.to_csv('pct65plus_region_25.csv', index=False)

growth: 65plus 25- 65plus23/65plus23

In [28]:
pct_65plus_by_region_23

                        Age 65 Plus 2023      Total  pct 65 plus
Region
Central North Carolina          597310.0  4090082.0    14.603864
Eastern North Carolina          124416.0   768185.0    16.196099
Western North Carolina           92030.0   443243.0    20.762877

In [29]:
race_age_groups_23.head(1)

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37019,Brunswick,Eastern North Carolina,Cape Fear Council of Governments,Wilmington,2023.0,Other,1.0,269.0,156.0,...,47.91,1448.0,395.0,881.0,1317.0,1684.0,"{""coordinates"":[[[[-78.16235,34.357006999],[-7...",NaN,NaN,NaN

In [30]:
region_grouped_23=race_age_groups_23[['County','Region','Year','Race','Age 65 Plus', 'Total']]

In [31]:
region_grouped_23

        County                  Region    Year   Race  Age 65 Plus    Total
0    Brunswick  Eastern North Carolina  2023.0  Other       1684.0   5725.0
1          NaN                     NaN     NaN    NaN          NaN      NaN
2      34.120"                Estimate     NaN    NaN          NaN      NaN
3     Cabarrus  Central North Carolina  2023.0  Other        614.0  11327.0
4     Alamance  Central North Carolina  2023.0  Black       6115.0  38581.0
..         ...                     ...     ...    ...          ...      ...
816      Macon  Western North Carolina  2023.0  White      10791.0  35524.0
817        NaN                     NaN     NaN    NaN          NaN      NaN
818   Estimate                    2023     NaN    NaN          NaN      NaN
819    Tyrrell  Eastern North Carolina  2023.0  White        614.0   2225.0
820      Surry  Western North Carolina  2023.0  Black        530.0   2867.0

[821 rows x 6 columns]

In [32]:
#region_grouped_23=new_race_age_groups_23[new_race_age_groups_23['County'].isin(NC_IRF_Counties_List)]
#region_grouped_23

region_grouped_23 = new_race_age_groups_23.groupby('Region').agg({'Age 65 Plus':'sum',
                                                                  'Total':'sum'})
region_grouped_23

In [33]:
region_grouped_24=race_age_groups_24[['County','Region','Year','Race','Age 65 Plus', 'Total']]
region_grouped_24

,County,Region,Year,Race,Age 65 Plus,Total
0,Alleghany,Western North Carolina,2024.0,White,3174.0,10930.0
1,Alleghany,Western North Carolina,2024.0,Other,73.0,689.0
2,Ashe,Western North Carolina,2024.0,Other,245.0,1211.0
3,"36.5""",Projection,NaN,NaN,NaN,NaN
4,Ashe,Western North Carolina,2024.0,White,7497.0,25589.0
...,...,...,...,...,...,...
624,Projection,2024,NaN,NaN,NaN,NaN
625,Lee,Central North Carolina,2024.0,White,10025.0,51269.0
626,Halifax,Eastern North Carolina,2024.0,Other,110.0,1557.0
627,Projection,2024,NaN,NaN,NaN,NaN
628,Montgomery,Central North Carolina,2024.0,Asian & Pacific Islander,45.0,487.0

In [34]:
#region_grouped_24=region_grouped_24[region_grouped_24['County'].isin(NC_IRF_Counties_List)]
#region_grouped_24

In [35]:
region_grouped_25=race_age_groups_25[['County','Region','Year','Race','Age 65 Plus', 'Total']]
region_grouped_25

,County,Region,Year,Race,Age 65 Plus,Total
0,Alexander,Western North Carolina,2025.0,Asian & Pacific Islander,35.0,438.0
1,Alamance,Central North Carolina,2025.0,Other,220.0,8688.0
2,Burke,Western North Carolina,2025.0,Black,953.0,5184.0
3,NaN,NaN,NaN,NaN,NaN,NaN
4,"35.""",Projection,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
824,Pitt,Eastern North Carolina,2025.0,Black,8576.0,65899.0
825,NaN,NaN,NaN,NaN,NaN,NaN
826,"35.50""",Projection,NaN,NaN,NaN,NaN
827,Wake,Central North Carolina,2025.0,Asian & Pacific Islander,12371.0,126357.0
828,Rowan,Central North Carolina,2025.0,Black,3659.0,25182.0

In [49]:
region_grouped_25.to_csv('region_grouped_25.csv', index=False)

In [36]:
#region_grouped_25=region_grouped_25[region_grouped_25['County'].isin(NC_IRF_Counties_List)]
#region_grouped_25

In [37]:
dfs=[region_grouped_23, region_grouped_24, region_grouped_25]

regions_grouped_merged = dfs[0]

for i in range(1, len(dfs)):
    regions_grouped_merged= pd.merge(regions_grouped_merged, dfs[i], on = 'County', how ='inner')


regions_grouped_merged

,County,Region_x,Year_x,Race_x,Age 65 Plus_x,Total_x,Region_y,Year_y,Race_y,Age 65 Plus_y,Total_y,Region,Year,Race,Age 65 Plus,Total
0,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,Asian & Pacific Islander,547.0,1471.0
1,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,Black,3789.0,13716.0
2,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,White,64842.0,151581.0
3,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,American Indian / Alaska Native,502.0,1482.0
4,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,Other,2262.0,6797.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26581,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,Black,562.0,2856.0
26582,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,Asian & Pacific Islander,58.0,506.0
26583,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,White,14391.0,65078.0
26584,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,Other,310.0,2568.0
26585,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,American Indian / Alaska Native,178.0,766.0

In [38]:
regions_grouped_merged=regions_grouped_merged.rename(columns={'Age 65 Plus_x':'Age 65 Plus 2023', 'Age 65 Plus_y':'Age 65 Plus 2024','Age 65 Plus':'Age 65 Plus 2025'})
regions_grouped_merged

,County,Region_x,Year_x,Race_x,Age 65 Plus 2023,Total_x,Region_y,Year_y,Race_y,Age 65 Plus 2024,Total_y,Region,Year,Race,Age 65 Plus 2025,Total
0,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,Asian & Pacific Islander,547.0,1471.0
1,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,Black,3789.0,13716.0
2,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,White,64842.0,151581.0
3,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,American Indian / Alaska Native,502.0,1482.0
4,Brunswick,Eastern North Carolina,2023.0,Other,1684.0,5725.0,Eastern North Carolina,2024.0,Other,1966.0,6261.0,Eastern North Carolina,2025.0,Other,2262.0,6797.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26581,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,Black,562.0,2856.0
26582,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,Asian & Pacific Islander,58.0,506.0
26583,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,White,14391.0,65078.0
26584,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,Other,310.0,2568.0
26585,Surry,Western North Carolina,2023.0,Black,530.0,2867.0,Western North Carolina,2024.0,Black,546.0,2861.0,Western North Carolina,2025.0,American Indian / Alaska Native,178.0,766.0

In [39]:
regions_grouped_merged= regions_grouped_merged[['County','Region', 'Age 65 Plus 2023','Age 65 Plus 2024','Age 65 Plus 2025']]
regions_grouped_merged

,County,Region,Age 65 Plus 2023,Age 65 Plus 2024,Age 65 Plus 2025
0,Brunswick,Eastern North Carolina,1684.0,1966.0,547.0
1,Brunswick,Eastern North Carolina,1684.0,1966.0,3789.0
2,Brunswick,Eastern North Carolina,1684.0,1966.0,64842.0
3,Brunswick,Eastern North Carolina,1684.0,1966.0,502.0
4,Brunswick,Eastern North Carolina,1684.0,1966.0,2262.0
...,...,...,...,...,...
26581,Surry,Western North Carolina,530.0,546.0,562.0
26582,Surry,Western North Carolina,530.0,546.0,58.0
26583,Surry,Western North Carolina,530.0,546.0,14391.0
26584,Surry,Western North Carolina,530.0,546.0,310.0
26585,Surry,Western North Carolina,530.0,546.0,178.0

In [40]:
regions_grouped_merged_two= regions_grouped_merged.groupby('Region').agg({'Age 65 Plus 2023':'sum',
                                                                          'Age 65 Plus 2024':'sum',
                                                                          'Age 65 Plus 2025':'sum'})
regions_grouped_merged_two

                        Age 65 Plus 2023  Age 65 Plus 2024  Age 65 Plus 2025
Region
Central North Carolina        22238064.0        23070716.0        23902441.0
Eastern North Carolina        12629311.0        13055185.0        13465703.0
Projection                           0.0               0.0               0.0
Western North Carolina        10346476.0        10551325.0        10746841.0

In [41]:
regions_grouped_merged_two['Pct growth 65 plus']= (regions_grouped_merged_two['Age 65 Plus 2025']-regions_grouped_merged_two['Age 65 Plus 2023'])/(regions_grouped_merged_two['Age 65 Plus 2023']) * 100

In [42]:
regions_grouped_merged_two=regions_grouped_merged_two.reset_index()
regions_grouped_merged_two

,Region,Age 65 Plus 2023,Age 65 Plus 2024,Age 65 Plus 2025,Pct growth 65 plus
0,Central North Carolina,22238064.0,23070716.0,23902441.0,7.484361
1,Eastern North Carolina,12629311.0,13055185.0,13465703.0,6.622626
2,Projection,0.0,0.0,0.0,NaN
3,Western North Carolina,10346476.0,10551325.0,10746841.0,3.869578

In [43]:
regions_grouped_merged_two=regions_grouped_merged_two.drop(2)

In [44]:
regions_grouped_merged_two

,Region,Age 65 Plus 2023,Age 65 Plus 2024,Age 65 Plus 2025,Pct growth 65 plus
0,Central North Carolina,22238064.0,23070716.0,23902441.0,7.484361
1,Eastern North Carolina,12629311.0,13055185.0,13465703.0,6.622626
3,Western North Carolina,10346476.0,10551325.0,10746841.0,3.869578

In [45]:
regions_grouped_merged_two.to_csv('regions_grouped_merged_two.csv', index=False)

Looking at where the IRFs are by NC region:

In [46]:
Inpatient_Rehabilitation_Facility-General_Information_Jun2025

NameError: name 'Inpatient_Rehabilitation_Facility' is not defined

In [ ]:
Provider_data_25=pd.read_csv('../data/Inpatient_Rehabilitation_Facility_Provider_Data_Jun2025.csv')
Provider_data_25

In [ ]:
NC_Provider_data_25=Provider_data_25.loc[Provider_data_25['State']=='NC']
NC_Provider_data_25

In [ ]:
NC_Provider_data_25['County/Parish'].nunique()

In [ ]:
NC_Provider_data_25['Provider Name'].nunique()

In [ ]:
unique_IRFs_per_county = NC_Provider_data_25.groupby('County/Parish')['Provider Name'].nunique().to_frame().reset_index()
unique_IRFs_per_county

In [ ]:
unique_IRFs_per_county=unique_IRFs_per_county.rename(columns={'Provider Name':'Number of IRFs'})
unique_IRFs_per_county

In [ ]:
NC_IRF_Counties_List=['Buncombe','Catawba','Craven','Cumberland','Durham','Forsyth','Guilford','Lenoir','Mecklenburg','Moore','Nash','New_Hanover','Orange','Pitt','Rowan','Vance','Wake']

In [ ]:
unique_IRFs_per_county=unique_IRFs_per_county[unique_IRFs_per_county['County/Parish'].isin(NC_IRF_Counties_List)]

In [ ]:
unique_IRFs_per_county.to_csv('unique_IRFs_per_county.csv', index=False)