In [1]:
import pandas as pd

In [2]:
#### This notebook will look at years 2023-2025 population of 65+ by regions: Eastern, Central, and Western North Carolin

In [3]:
pop_projections_2023=pd.read_csv('../data/population-projections-by-race-age-groups_2023.csv')
pop_projections_2023.head()

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37019,Brunswick,Eastern North Carolina,Cape Fear Council of Governments,Wilmington,2023,Other,1,269,156,...,47.910000,1448,395,881,1317,1684,"{""coordinates"":[[[[-78.16235,34.357006999],[-7...",Estimate,2023,"34.03887554891685, -78.22740741677175"
1,37025,Cabarrus,Central North Carolina,Centralina Council of Governments,Charlotte-Concord-Gastonia (NC),2023,Other,1,960,581,...,20.226829,5183,1245,2469,1816,614,"{""coordinates"":[[[[-80.784167,35.506016999],[-...",Estimate,2023,"35.38678374966464, -80.55187904089568"
2,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2023,Black,1,1364,970,...,38.610647,9517,3529,9046,10374,6115,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Estimate,2023,"36.04370973725824, -79.39942485544303"
3,37019,Brunswick,Eastern North Carolina,Cape Fear Council of Governments,Wilmington,2023,Black,1,389,257,...,46.468182,2401,870,3082,3459,3215,"{""coordinates"":[[[[-78.16235,34.357006999],[-7...",Estimate,2023,"34.03887554891685, -78.22740741677175"
4,37083,Halifax,Eastern North Carolina,Upper Coastal Plain Council of Governments,Non-Metropolitan,2023,Asian & Pacific Islander,1,6,6,...,54.100000,67,35,12,92,81,"{""coordinates"":[[[[-77.899524,36.504258999],[-...",Estimate,2023,"36.257448525751315, -77.65173263517927"

In [4]:
pop_projection_2024=pd.read_csv('../data/population-projections-by-race-age-groups_2024.csv')
pop_projection_2024.head()

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37005,Alleghany,Western North Carolina,High Country Council of Governments,Non-Metropolitan,2024,White,1,278,166,...,50.259542,1733,700,2420,2903,3174,"{""coordinates"":[[[[-81.353259,36.574691999],[-...",Projection,2024,"36.491541528612935, -81.12701608444002"
1,37005,Alleghany,Western North Carolina,High Country Council of Governments,Non-Metropolitan,2024,Other,4,41,23,...,28.318182,246,66,187,117,73,"{""coordinates"":[[[[-81.353259,36.574691999],[-...",Projection,2024,"36.491541528612935, -81.12701608444002"
2,37009,Ashe,Western North Carolina,High Country Council of Governments,Non-Metropolitan,2024,Other,4,62,42,...,36.884615,350,108,240,268,245,"{""coordinates"":[[[[-81.67749,36.588136999],[-8...",Projection,2024,"36.4340927486132, -81.50038428304501"
3,37009,Ashe,Western North Carolina,High Country Council of Governments,Non-Metropolitan,2024,White,1,547,392,...,50.794408,4053,1701,5318,7020,7497,"{""coordinates"":[[[[-81.67749,36.588136999],[-8...",Projection,2024,"36.4340927486132, -81.50038428304501"
4,37079,Greene,Eastern North Carolina,Eastern Carolina Council of Governments,Non-Metropolitan,2024,Other,2,76,53,...,13.537037,394,55,148,59,19,"{""coordinates"":[[[[-77.700692,35.652294999],[-...",Projection,2024,"35.484995419375394, -77.67576264299726"

In [5]:
pop_projection_2025=pd.read_csv('../data/population-projections-by-race-age-groups-2025.csv')
pop_projection_2025.head()

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37003,Alexander,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2025,Asian & Pacific Islander,1,17,12,...,34.272727,100,38,171,94,35,"{""coordinates"":[[[[-81.328324,35.996582999],[-...",Projection,2024,"35.921026310411975, -81.17702681231853"
1,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2025,Other,1,690,444,...,17.453125,4449,1080,1997,942,220,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Projection,2024,"36.04370973725824, -79.39942485544303"
2,37023,Burke,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2025,Black,1,123,91,...,36.940299,1190,723,1001,1317,953,"{""coordinates"":[[[[-81.943188,35.960049999],[-...",Projection,2024,"35.74961065992926, -81.70477863312823"
3,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2025,White,1,3686,2414,...,40.754580,24346,15378,31779,32814,25378,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Projection,2024,"36.04370973725824, -79.39942485544303"
4,37089,Henderson,Western North Carolina,Land-of-Sky Regional Council,Asheville,2025,Black,1,121,82,...,42.279661,927,373,1073,1111,967,"{""coordinates"":[[[[-82.265795,35.467817999],[-...",Projection,2024,"35.33622624878542, -82.47994628552264"

Starting with 2023

In [6]:
pop_projections_2023.head(3)

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37019,Brunswick,Eastern North Carolina,Cape Fear Council of Governments,Wilmington,2023,Other,1,269,156,...,47.910000,1448,395,881,1317,1684,"{""coordinates"":[[[[-78.16235,34.357006999],[-7...",Estimate,2023,"34.03887554891685, -78.22740741677175"
1,37025,Cabarrus,Central North Carolina,Centralina Council of Governments,Charlotte-Concord-Gastonia (NC),2023,Other,1,960,581,...,20.226829,5183,1245,2469,1816,614,"{""coordinates"":[[[[-80.784167,35.506016999],[-...",Estimate,2023,"35.38678374966464, -80.55187904089568"
2,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2023,Black,1,1364,970,...,38.610647,9517,3529,9046,10374,6115,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Estimate,2023,"36.04370973725824, -79.39942485544303"

In [7]:
pop_projections_2023.columns

Index(['fips', 'County', 'Region', 'COG', 'MSA', 'Year', 'Race', 'Group N',
       'Age 0 to 2', 'Age 3 to 4', 'Age 5', 'Age 6 to 9', 'Age 10 to 13',
       'Age 14', 'Age 15', 'Age 16 to 17', 'Age 18 to 19', 'Age 20 to 24',
       'Age 25 to 34', 'Age 35 to 44', 'Age 45 to 54', 'Age 55 to 59',
       'Age 60 to 64', 'Age 65 to 74', 'Age 75 to 84', 'Age 85 to 99',
       'Age 100', 'Total', 'medage', 'Age 0 to 17', 'Age 18 to 24',
       'Age 25 to 44', 'Age 45 to 64', 'Age 65 Plus', 'geom',
       'Estimate/Projection', 'Vintage', 'geo_point_2d'],
      dtype='object')

In [8]:
region_NC_23=pop_projections_2023[['County','Region','Age 65 Plus','Total','Year']]
region_NC_23

         County                  Region  Age 65 Plus  Total  Year
0     Brunswick  Eastern North Carolina         1684   5725  2023
1      Cabarrus  Central North Carolina          614  11327  2023
2      Alamance  Central North Carolina         6115  38581  2023
3     Brunswick  Eastern North Carolina         3215  13027  2023
4       Halifax  Eastern North Carolina           81    287  2023
..          ...                     ...          ...    ...   ...
424     Iredell  Western North Carolina          766   8408  2023
425  Pasquotank  Eastern North Carolina           96    546  2023
426       Macon  Western North Carolina        10791  35524  2023
427     Tyrrell  Eastern North Carolina          614   2225  2023
428       Surry  Western North Carolina          530   2867  2023

[429 rows x 5 columns]

In [9]:
NC_IRF_Counties_List=['Buncombe','Catawba','Craven','Cumberland','Durham','Forsyth','Guilford','Lenoir','Mecklenburg','Moore','Nash','New_Hanover','Orange','Pitt','Rowan','Vance','Wake']

In [10]:
region_NC_23= region_NC_23[region_NC_23['County'].isin(NC_IRF_Counties_List)]
region_NC_23

       County                  Region  Age 65 Plus   Total  Year
11    Catawba  Western North Carolina         1091    7825  2023
17     Craven  Eastern North Carolina          679    3802  2023
33   Guilford  Central North Carolina         3123   32699  2023
39   Buncombe  Western North Carolina        54841  241346  2023
50   Buncombe  Western North Carolina         2797   16517  2023
..        ...                     ...          ...     ...   ...
384  Guilford  Central North Carolina         1054   22430  2023
387   Forsyth  Central North Carolina         1133   11241  2023
388     Rowan  Central North Carolina        22785  117253  2023
391   Forsyth  Central North Carolina        52299  259712  2023
398    Durham  Central North Carolina        29830  182995  2023

[80 rows x 5 columns]

#### Finding the percent of the population that is 65+ by region, and percent growth of 65+ by region

In [11]:
region_NC_23_totalpop=region_NC_23.groupby('Region')['Total'].sum()
region_NC_23_totalpop

Region
Central North Carolina    4090082
Eastern North Carolina     768185
Western North Carolina     443243
Name: Total, dtype: int64

In [12]:
region_NC_23_totalpop=region_NC_23_totalpop.to_frame()
region_NC_23_totalpop

                          Total
Region
Central North Carolina  4090082
Eastern North Carolina   768185
Western North Carolina   443243

In [13]:
region_NC_23_pct65= region_NC_23.groupby('Region')['Age 65 Plus'].sum().to_frame()
region_NC_23_pct65

                        Age 65 Plus
Region
Central North Carolina       597310
Eastern North Carolina       124416
Western North Carolina        92030

In [14]:
region_NC_23_pct65=region_NC_23_pct65.rename(columns={'Age 65 Plus':'Age 65 Plus 2023'})
region_NC_23_pct65

                        Age 65 Plus 2023
Region
Central North Carolina            597310
Eastern North Carolina            124416
Western North Carolina             92030

In [15]:
pct_65plus_by_region_23=pd.merge(region_NC_23_pct65, region_NC_23_totalpop,
                      on='Region',
                      how='inner')
pct_65plus_by_region_23

                        Age 65 Plus 2023    Total
Region
Central North Carolina            597310  4090082
Eastern North Carolina            124416   768185
Western North Carolina             92030   443243

In [16]:
pct_65plus_by_region_23['pct 65 plus']=(pct_65plus_by_region_23['Age 65 Plus 2023'])/(pct_65plus_by_region_23['Total']) * 100
pct_65plus_by_region_23

                        Age 65 Plus 2023    Total  pct 65 plus
Region
Central North Carolina            597310  4090082    14.603864
Eastern North Carolina            124416   768185    16.196099
Western North Carolina             92030   443243    20.762877

In [17]:
pct_65plus_by_region_23.to_csv('pct_65plus_by_region_23.csv', index=True)

#### 2024

In [18]:
region_NC_24=pop_projection_2024[['County','Region','Age 65 Plus','Total']]
region_NC_24

         County                  Region  Age 65 Plus  Total
0     Alleghany  Western North Carolina         3174  10930
1     Alleghany  Western North Carolina           73    689
2          Ashe  Western North Carolina          245   1211
3          Ashe  Western North Carolina         7497  25589
4        Greene  Eastern North Carolina           19    675
..          ...                     ...          ...    ...
426  Perquimans  Eastern North Carolina          528   2644
427      Onslow  Eastern North Carolina          224   2619
428         Lee  Central North Carolina        10025  51269
429     Halifax  Eastern North Carolina          110   1557
430  Montgomery  Central North Carolina           45    487

[431 rows x 4 columns]

In [19]:
region_NC_24= region_NC_24[region_NC_24['County'].isin(NC_IRF_Counties_List)]
region_NC_24

       County                  Region  Age 65 Plus   Total
8     Forsyth  Central North Carolina        53654  260710
18   Guilford  Central North Carolina         1093   23287
21     Durham  Central North Carolina          405   14120
26   Buncombe  Western North Carolina         2861   16610
33   Guilford  Central North Carolina        63906  300653
..        ...                     ...          ...     ...
394     Rowan  Central North Carolina        23282  117634
396    Durham  Central North Carolina         1998   19481
403    Orange  Central North Carolina         1146   14366
417      Wake  Central North Carolina        11414  121008
418      Wake  Central North Carolina        25607  219853

[80 rows x 4 columns]

In [20]:
region_NC_24_totalpop=region_NC_24.groupby('Region')['Total'].sum().to_frame()
region_NC_24_totalpop

                          Total
Region
Central North Carolina  4145178
Eastern North Carolina   769000
Western North Carolina   448087

In [21]:
region_NC_24_pct65= region_NC_24.groupby('Region')['Age 65 Plus'].sum().to_frame()
region_NC_24_pct65

                        Age 65 Plus
Region
Central North Carolina       621304
Eastern North Carolina       126683
Western North Carolina        94654

In [22]:
pct65plus_region_24=pd.merge(region_NC_24_totalpop,region_NC_24_pct65,
                             on='Region',
                             how= 'inner')
pct65plus_region_24

                          Total  Age 65 Plus
Region
Central North Carolina  4145178       621304
Eastern North Carolina   769000       126683
Western North Carolina   448087        94654

In [23]:
pct65plus_region_24['pct 65 plus']= ((pct65plus_region_24['Age 65 Plus']/pct65plus_region_24['Total']) * 100)
pct65plus_region_24

                          Total  Age 65 Plus  pct 65 plus
Region
Central North Carolina  4145178       621304    14.988596
Eastern North Carolina   769000       126683    16.473732
Western North Carolina   448087        94654    21.124023

In [24]:
pct65plus_region_24=pct65plus_region_24.rename(columns={'Age 65 Plus':'Age 65 Plus 2024'}).reset_index()
pct65plus_region_24

                   Region    Total  Age 65 Plus 2024  pct 65 plus
0  Central North Carolina  4145178            621304    14.988596
1  Eastern North Carolina   769000            126683    16.473732
2  Western North Carolina   448087             94654    21.124023

In [25]:
pop_projection_2025.head()

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37003,Alexander,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2025,Asian & Pacific Islander,1,17,12,...,34.272727,100,38,171,94,35,"{""coordinates"":[[[[-81.328324,35.996582999],[-...",Projection,2024,"35.921026310411975, -81.17702681231853"
1,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2025,Other,1,690,444,...,17.453125,4449,1080,1997,942,220,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Projection,2024,"36.04370973725824, -79.39942485544303"
2,37023,Burke,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2025,Black,1,123,91,...,36.940299,1190,723,1001,1317,953,"{""coordinates"":[[[[-81.943188,35.960049999],[-...",Projection,2024,"35.74961065992926, -81.70477863312823"
3,37001,Alamance,Central North Carolina,Piedmont Triad Council of Governments,Burlington,2025,White,1,3686,2414,...,40.754580,24346,15378,31779,32814,25378,"{""coordinates"":[[[[-79.53241,36.241462999],[-7...",Projection,2024,"36.04370973725824, -79.39942485544303"
4,37089,Henderson,Western North Carolina,Land-of-Sky Regional Council,Asheville,2025,Black,1,121,82,...,42.279661,927,373,1073,1111,967,"{""coordinates"":[[[[-82.265795,35.467817999],[-...",Projection,2024,"35.33622624878542, -82.47994628552264"

In [26]:
region_NC_25=pop_projection_2025[['County','Region','Age 65 Plus','Total']]
region_NC_25

        County                  Region  Age 65 Plus   Total
0    Alexander  Western North Carolina           35     438
1     Alamance  Central North Carolina          220    8688
2        Burke  Western North Carolina          953    5184
3     Alamance  Central North Carolina        25378  129695
4    Henderson  Western North Carolina          967    4451
..         ...                     ...          ...     ...
428   Caldwell  Western North Carolina           97     691
429       Hyde  Eastern North Carolina          293    1125
430       Pitt  Eastern North Carolina         8576   65899
431       Wake  Central North Carolina        12371  126357
432      Rowan  Central North Carolina         3659   25182

[433 rows x 4 columns]

In [27]:
region_NC_25= region_NC_25[region_NC_25['County'].isin(NC_IRF_Counties_List)]
region_NC_25

         County                  Region  Age 65 Plus   Total
11   Cumberland  Eastern North Carolina        25406  161147
18       Lenoir  Eastern North Carolina         7133   29126
21      Forsyth  Central North Carolina          490   17861
27   Cumberland  Eastern North Carolina          818    7080
33     Buncombe  Western North Carolina        57666  245397
..          ...                     ...          ...     ...
404      Durham  Central North Carolina         2115   19899
405       Vance  Central North Carolina           57    1312
430        Pitt  Eastern North Carolina         8576   65899
431        Wake  Central North Carolina        12371  126357
432       Rowan  Central North Carolina         3659   25182

[80 rows x 4 columns]

In [28]:
region_NC_25_totalpop=region_NC_25.groupby('Region')['Total'].sum().to_frame()
region_NC_25_totalpop

                          Total
Region
Central North Carolina  4202985
Eastern North Carolina   770585
Western North Carolina   452938

In [29]:
region_NC_25_pct65= region_NC_25.groupby('Region')['Age 65 Plus'].sum().to_frame()
region_NC_25_pct65

                        Age 65 Plus
Region
Central North Carolina       645285
Eastern North Carolina       128896
Western North Carolina        97185

In [30]:
region_NC_25_pct65=region_NC_25_pct65.rename(columns={'Age 65 Plus':'Age 65 Plus 2025'})
region_NC_25_pct65

                        Age 65 Plus 2025
Region
Central North Carolina            645285
Eastern North Carolina            128896
Western North Carolina             97185

In [31]:
pct65plus_region_25=pd.merge(region_NC_25_totalpop,region_NC_25_pct65,
                             on='Region',
                             how= 'inner')
pct65plus_region_25

                          Total  Age 65 Plus 2025
Region
Central North Carolina  4202985            645285
Eastern North Carolina   770585            128896
Western North Carolina   452938             97185

In [32]:
pct65plus_region_25['pct 65 plus']= (pct65plus_region_25['Age 65 Plus 2025']/pct65plus_region_25['Total']) * 100
pct65plus_region_25

                          Total  Age 65 Plus 2025  pct 65 plus
Region
Central North Carolina  4202985            645285    15.353017
Eastern North Carolina   770585            128896    16.727032
Western North Carolina   452938             97185    21.456579

In [33]:
pct65plus_region_25=pct65plus_region_25.reset_index()
pct65plus_region_25

                   Region    Total  Age 65 Plus 2025  pct 65 plus
0  Central North Carolina  4202985            645285    15.353017
1  Eastern North Carolina   770585            128896    16.727032
2  Western North Carolina   452938             97185    21.456579

In [34]:
pct65plus_region_25.to_csv('pct65plus_region_25.csv', index=False)

In [35]:
pct65plus_region_24

                   Region    Total  Age 65 Plus 2024  pct 65 plus
0  Central North Carolina  4145178            621304    14.988596
1  Eastern North Carolina   769000            126683    16.473732
2  Western North Carolina   448087             94654    21.124023

In [36]:
pct_65plus_by_region_23

                        Age 65 Plus 2023    Total  pct 65 plus
Region
Central North Carolina            597310  4090082    14.603864
Eastern North Carolina            124416   768185    16.196099
Western North Carolina             92030   443243    20.762877

In [37]:
dfs=[pct_65plus_by_region_23, pct65plus_region_24, pct65plus_region_25]

percent_65plus_region = dfs[0]

for i in range(1, len(dfs)):
    percent_65plus_region= pd.merge(percent_65plus_region, dfs[i], on = 'Region', how ='inner')


percent_65plus_region

,Region,Age 65 Plus 2023,Total_x,pct 65 plus_x,Total_y,Age 65 Plus 2024,pct 65 plus_y,Total,Age 65 Plus 2025,pct 65 plus
0,Central North Carolina,597310,4090082,14.603864,4145178,621304,14.988596,4202985,645285,15.353017
1,Eastern North Carolina,124416,768185,16.196099,769000,126683,16.473732,770585,128896,16.727032
2,Western North Carolina,92030,443243,20.762877,448087,94654,21.124023,452938,97185,21.456579

In [38]:
percent_65plus_region=percent_65plus_region[['Region', 'pct 65 plus_x', 'pct 65 plus_y','pct 65 plus']]
percent_65plus_region

                   Region  pct 65 plus_x  pct 65 plus_y  pct 65 plus
0  Central North Carolina      14.603864      14.988596    15.353017
1  Eastern North Carolina      16.196099      16.473732    16.727032
2  Western North Carolina      20.762877      21.124023    21.456579

In [39]:
percent_65plus_region=percent_65plus_region.rename(columns={'pct 65 plus_x':'pct 65 plus 2023','pct 65 plus_y':'pct 65 plus 2024','pct 65 plus':'pct 65 plus 2025'})
percent_65plus_region

,Region,pct 65 plus 2023,pct 65 plus 2024,pct 65 plus 2025
0,Central North Carolina,14.603864,14.988596,15.353017
1,Eastern North Carolina,16.196099,16.473732,16.727032
2,Western North Carolina,20.762877,21.124023,21.456579

#### Finding the Percent growth of age 65 plus from '23-'25 by region

In [40]:
pop_projections_2023.head(1)

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37019,Brunswick,Eastern North Carolina,Cape Fear Council of Governments,Wilmington,2023,Other,1,269,156,...,47.91,1448,395,881,1317,1684,"{""coordinates"":[[[[-78.16235,34.357006999],[-7...",Estimate,2023,"34.03887554891685, -78.22740741677175"

In [41]:
region_grouped_23=pop_projections_2023[['County','Region','Year','Race','Age 65 Plus', 'Total']]

In [42]:
region_grouped_23

,County,Region,Year,Race,Age 65 Plus,Total
0,Brunswick,Eastern North Carolina,2023,Other,1684,5725
1,Cabarrus,Central North Carolina,2023,Other,614,11327
2,Alamance,Central North Carolina,2023,Black,6115,38581
3,Brunswick,Eastern North Carolina,2023,Black,3215,13027
4,Halifax,Eastern North Carolina,2023,Asian & Pacific Islander,81,287
...,...,...,...,...,...,...
424,Iredell,Western North Carolina,2023,Other,766,8408
425,Pasquotank,Eastern North Carolina,2023,Asian & Pacific Islander,96,546
426,Macon,Western North Carolina,2023,White,10791,35524
427,Tyrrell,Eastern North Carolina,2023,White,614,2225
428,Surry,Western North Carolina,2023,Black,530,2867

In [44]:
region_grouped_24=pop_projection_2024[['County','Region','Year','Race','Age 65 Plus', 'Total']]
region_grouped_24

,County,Region,Year,Race,Age 65 Plus,Total
0,Alleghany,Western North Carolina,2024,White,3174,10930
1,Alleghany,Western North Carolina,2024,Other,73,689
2,Ashe,Western North Carolina,2024,Other,245,1211
3,Ashe,Western North Carolina,2024,White,7497,25589
4,Greene,Eastern North Carolina,2024,Other,19,675
...,...,...,...,...,...,...
426,Perquimans,Eastern North Carolina,2024,Black,528,2644
427,Onslow,Eastern North Carolina,2024,American Indian / Alaska Native,224,2619
428,Lee,Central North Carolina,2024,White,10025,51269
429,Halifax,Eastern North Carolina,2024,Other,110,1557
430,Montgomery,Central North Carolina,2024,Asian & Pacific Islander,45,487

In [46]:
region_grouped_25=pop_projection_2025[['County','Region','Year','Race','Age 65 Plus', 'Total']]
region_grouped_25

,County,Region,Year,Race,Age 65 Plus,Total
0,Alexander,Western North Carolina,2025,Asian & Pacific Islander,35,438
1,Alamance,Central North Carolina,2025,Other,220,8688
2,Burke,Western North Carolina,2025,Black,953,5184
3,Alamance,Central North Carolina,2025,White,25378,129695
4,Henderson,Western North Carolina,2025,Black,967,4451
...,...,...,...,...,...,...
428,Caldwell,Western North Carolina,2025,Asian & Pacific Islander,97,691
429,Hyde,Eastern North Carolina,2025,Black,293,1125
430,Pitt,Eastern North Carolina,2025,Black,8576,65899
431,Wake,Central North Carolina,2025,Asian & Pacific Islander,12371,126357
432,Rowan,Central North Carolina,2025,Black,3659,25182

In [47]:
region_grouped_25.to_csv('region_grouped_25.csv', index=False)

In [49]:
dfs=[region_grouped_23, region_grouped_24, region_grouped_25]

regions_grouped_merged = dfs[0]

for i in range(1, len(dfs)):
    regions_grouped_merged= pd.merge(regions_grouped_merged, dfs[i], on = 'County', how ='inner')


regions_grouped_merged

,County,Region_x,Year_x,Race_x,Age 65 Plus_x,Total_x,Region_y,Year_y,Race_y,Age 65 Plus_y,Total_y,Region,Year,Race,Age 65 Plus,Total
0,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,Asian & Pacific Islander,547,1471
1,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,Black,3789,13716
2,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,White,64842,151581
3,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,American Indian / Alaska Native,502,1482
4,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,Other,2262,6797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9127,Surry,Western North Carolina,2023,Black,530,2867,Western North Carolina,2024,Black,546,2861,Western North Carolina,2025,Black,562,2856
9128,Surry,Western North Carolina,2023,Black,530,2867,Western North Carolina,2024,Black,546,2861,Western North Carolina,2025,Asian & Pacific Islander,58,506
9129,Surry,Western North Carolina,2023,Black,530,2867,Western North Carolina,2024,Black,546,2861,Western North Carolina,2025,White,14391,65078
9130,Surry,Western North Carolina,2023,Black,530,2867,Western North Carolina,2024,Black,546,2861,Western North Carolina,2025,Other,310,2568
9131,Surry,Western North Carolina,2023,Black,530,2867,Western North Carolina,2024,Black,546,2861,Western North Carolina,2025,American Indian / Alaska Native,178,766

In [50]:
regions_grouped_merged=regions_grouped_merged.rename(columns={'Age 65 Plus_x':'Age 65 Plus 2023', 'Age 65 Plus_y':'Age 65 Plus 2024','Age 65 Plus':'Age 65 Plus 2025'})
regions_grouped_merged.head()

,County,Region_x,Year_x,Race_x,Age 65 Plus 2023,Total_x,Region_y,Year_y,Race_y,Age 65 Plus 2024,Total_y,Region,Year,Race,Age 65 Plus 2025,Total
0,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,Asian & Pacific Islander,547,1471
1,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,Black,3789,13716
2,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,White,64842,151581
3,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,American Indian / Alaska Native,502,1482
4,Brunswick,Eastern North Carolina,2023,Other,1684,5725,Eastern North Carolina,2024,Other,1966,6261,Eastern North Carolina,2025,Other,2262,6797

In [51]:
regions_grouped_merged= regions_grouped_merged[['County','Region', 'Age 65 Plus 2023','Age 65 Plus 2024','Age 65 Plus 2025']]
regions_grouped_merged.head()

,County,Region,Age 65 Plus 2023,Age 65 Plus 2024,Age 65 Plus 2025
0,Brunswick,Eastern North Carolina,1684,1966,547
1,Brunswick,Eastern North Carolina,1684,1966,3789
2,Brunswick,Eastern North Carolina,1684,1966,64842
3,Brunswick,Eastern North Carolina,1684,1966,502
4,Brunswick,Eastern North Carolina,1684,1966,2262

In [52]:
regions_grouped_merged_two= regions_grouped_merged.groupby('Region').agg({'Age 65 Plus 2023':'sum',
                                                                          'Age 65 Plus 2024':'sum',
                                                                          'Age 65 Plus 2025':'sum'})
regions_grouped_merged_two

                        Age 65 Plus 2023  Age 65 Plus 2024  Age 65 Plus 2025
Region
Central North Carolina          22238064          23070716          23902441
Eastern North Carolina          12629311          13055185          13465703
Western North Carolina          10346476          10551325          10746841

In [53]:
regions_grouped_merged_two['Pct growth 65 plus']= (regions_grouped_merged_two['Age 65 Plus 2025']-regions_grouped_merged_two['Age 65 Plus 2023'])/(regions_grouped_merged_two['Age 65 Plus 2023']) * 100

In [54]:
regions_grouped_merged_two=regions_grouped_merged_two.reset_index()
regions_grouped_merged_two

,Region,Age 65 Plus 2023,Age 65 Plus 2024,Age 65 Plus 2025,Pct growth 65 plus
0,Central North Carolina,22238064,23070716,23902441,7.484361
1,Eastern North Carolina,12629311,13055185,13465703,6.622626
2,Western North Carolina,10346476,10551325,10746841,3.869578

In [55]:
regions_grouped_merged_two.to_csv('regions_grouped_merged_two.csv', index=False)

#### Looking at where the IRFs are by NC region:

In [68]:
Provider_data_25=pd.read_csv('../data/Inpatient_Rehabilitation_Facility_Provider_Data_Jun2025.csv')
Provider_data_25.head()

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.821,-,7/1/2023,6/30/2024,-
1,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_UPPER,4.213,-,7/1/2023,6/30/2024,-
2,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_COMP_PERF,No Different than the National Benchmark,-,7/1/2023,6/30/2024,-
3,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_DOPC_DAYS,"2,743",-,7/1/2023,6/30/2024,-
4,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_ELIGCASES,2.962,-,7/1/2023,6/30/2024,-

In [69]:
NC_Provider_data_25=Provider_data_25.loc[Provider_data_25['State']=='NC']
NC_Provider_data_25.head()

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
48552,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,I_006_01_CI_LOWER,0.381,-,7/1/2023,6/30/2024,-
48553,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,I_006_01_CI_UPPER,4.078,-,7/1/2023,6/30/2024,-
48554,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,I_006_01_COMP_PERF,No Different than the National Benchmark,-,7/1/2023,6/30/2024,-
48555,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,I_006_01_DOPC_DAYS,895,-,7/1/2023,6/30/2024,-
48556,343025,CAREPARTNERS REHABILITATION HOSPITAL,68 SWEETEN CREEK RD,-,ASHEVILLE,NC,28813,Buncombe,(828) 274-2400,4,I_006_01_ELIGCASES,2.002,-,7/1/2023,6/30/2024,-

In [58]:
NC_Provider_data_25['County/Parish'].nunique()

19

In [59]:
NC_Provider_data_25['Provider Name'].nunique()

26

#### Finding which counties are in the NC Provider Data to keep consistency throughout my analysis:

In [60]:
unique_IRFs_per_county = NC_Provider_data_25.groupby('County/Parish')['Provider Name'].nunique().to_frame().reset_index()
unique_IRFs_per_county

   County/Parish  Provider Name
0       Buncombe              1
1        Catawba              2
2         Craven              1
3     Cumberland              1
4         Durham              1
5        Forsyth              3
6       Guilford              2
7         Lenoir              1
8    Mecklenburg              4
9          Moore              1
10          Nash              1
11   New Hanover              1
12        Orange              1
13          Pitt              1
14         Rowan              1
15      Scotland              1
16         Surry              1
17         Vance              1
18          Wake              1

In [66]:
unique_IRFs_per_county=unique_IRFs_per_county.rename(columns={'Provider Name':'Number of IRFs'})
unique_IRFs_per_county.head()

  County/Parish  Number of IRFs
0      Buncombe               1
1       Catawba               2
2        Craven               1
3    Cumberland               1
4        Durham               1

In [62]:
NC_IRF_Counties_List=['Buncombe','Catawba','Craven','Cumberland','Durham','Forsyth','Guilford','Lenoir','Mecklenburg','Moore','Nash','New_Hanover','Orange','Pitt','Rowan','Vance','Wake']

In [67]:
unique_IRFs_per_county=unique_IRFs_per_county[unique_IRFs_per_county['County/Parish'].isin(NC_IRF_Counties_List)]

In [64]:
unique_IRFs_per_county.to_csv('unique_IRFs_per_county.csv', index=False)